export const KEYFRAME_PROPERTIES = {
  POSITION_X: 'position.x',
  POSITION_Y: 'position.y',
  SCALE_X: 'scale.x',
  SCALE_Y: 'scale.y',
  ROTATION: 'rotation',
  OPACITY: 'opacity',
  BRIGHTNESS: 'brightness',
  CONTRAST: 'contrast',
  SATURATION: 'saturation',
  VOLUME: 'volume',
  EFFECT_INTENSITY: 'effectIntensity',
};

export const INTERPOLATION_TYPES = {
  LINEAR: 'linear',
  EASE_IN: 'easeIn',
  EASE_OUT: 'easeOut',
  EASE_IN_OUT: 'easeInOut',
  HOLD: 'hold',
};

export const DEFAULT_KEYFRAME_VALUE_BY_PROPERTY = {
  [KEYFRAME_PROPERTIES.POSITION_X]: 0,
  [KEYFRAME_PROPERTIES.POSITION_Y]: 0,
  [KEYFRAME_PROPERTIES.SCALE_X]: 100,
  [KEYFRAME_PROPERTIES.SCALE_Y]: 100,
  [KEYFRAME_PROPERTIES.ROTATION]: 0,
  [KEYFRAME_PROPERTIES.OPACITY]: 100,
  [KEYFRAME_PROPERTIES.BRIGHTNESS]: 50,
  [KEYFRAME_PROPERTIES.CONTRAST]: 50,
  [KEYFRAME_PROPERTIES.SATURATION]: 50,
  [KEYFRAME_PROPERTIES.VOLUME]: 100,
  [KEYFRAME_PROPERTIES.EFFECT_INTENSITY]: 50,
};
