// =============================================================================
// registry.js — SPX Plugin Registry — All 106 Plugins
// =============================================================================

const pluginRegistry = {
  'a_i_compressor': {
    id: 'a_i_compressor',
    name: 'AICompressor',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'threshold', label: 'Threshold', type: 'float', min: -40, max: 0, default: -18, unit: 'dB', step: 0.5 },
      { id: 'ratio', label: 'Ratio', type: 'float', min: 1, max: 20, default: 4, unit: ':1', step: 0.1 },
      { id: 'attack', label: 'Attack', type: 'float', min: 0.1, max: 200, default: 10, unit: 'ms', step: 0.1 },
      { id: 'release', label: 'Release', type: 'float', min: 10, max: 2000, default: 150, unit: 'ms', step: 1 },
      { id: 'makeup', label: 'Makeup', type: 'float', min: 0, max: 24, default: 0, unit: 'dB', step: 0.5 },
      { id: 'style', label: 'Style', type: 'float', min: 0, max: 3, default: 0, unit: '', step: 1 },
    ],
    ui: { component: 'AICompressorPluginUI', width: 320, height: 200 },
  },

  'a_i_de_room': {
    id: 'a_i_de_room',
    name: 'AIDeRoom',
    version: '2.0.0',
    category: 'restoration',
    type: 'insert',
    color: '#44ddff',
    processor: { kind: 'native' },
    params: [
      { id: 'reduction', label: 'Reduction', type: 'float', min: 0, max: 1, default: 0.6, unit: '', step: 0.01 },
      { id: 'sensitivity', label: 'Sensitivity', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'freq', label: 'Freq', type: 'float', min: 200, max: 2000, default: 400, unit: 'Hz', step: 10 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'AIDeRoomPluginUI', width: 320, height: 200 },
  },

  'a_i_e_q_match': {
    id: 'a_i_e_q_match',
    name: 'AIEQMatch',
    version: '2.0.0',
    category: 'eq',
    type: 'insert',
    color: '#5ac8fa',
    processor: { kind: 'native' },
    params: [
      { id: 'match', label: 'Match', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'smoothing', label: 'Smoothing', type: 'float', min: 0, max: 1, default: 0.7, unit: '', step: 0.01 },
      { id: 'lowEnd', label: 'Lowend', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'highEnd', label: 'Highend', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
    ],
    ui: { component: 'AIEQMatchPluginUI', width: 320, height: 200 },
  },

  'a_i_noise_reduce': {
    id: 'a_i_noise_reduce',
    name: 'AINoiseReduce',
    version: '2.0.0',
    category: 'restoration',
    type: 'insert',
    color: '#44ddff',
    processor: { kind: 'native' },
    params: [
      { id: 'reduction', label: 'Reduction', type: 'float', min: 0, max: 1, default: 0.6, unit: '', step: 0.01 },
      { id: 'threshold', label: 'Threshold', type: 'float', min: -80, max: 0, default: -40, unit: 'dB', step: 0.5 },
      { id: 'smoothing', label: 'Smoothing', type: 'float', min: 0, max: 1, default: 0.8, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'AINoiseReducePluginUI', width: 320, height: 200 },
  },

  'a_i_vocal_clean': {
    id: 'a_i_vocal_clean',
    name: 'AIVocalClean',
    version: '2.0.0',
    category: 'vocal',
    type: 'insert',
    color: '#ff99cc',
    processor: { kind: 'native' },
    params: [
      { id: 'denoise', label: 'Denoise', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'debreath', label: 'Debreath', type: 'float', min: 0, max: 1, default: 0.3, unit: '', step: 0.01 },
      { id: 'declick', label: 'Declick', type: 'float', min: 0, max: 1, default: 0.3, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'AIVocalCleanPluginUI', width: 320, height: 200 },
  },

  'air_e_q': {
    id: 'air_e_q',
    name: 'AirEQ',
    version: '2.0.0',
    category: 'eq',
    type: 'insert',
    color: '#5ac8fa',
    processor: { kind: 'native' },
    params: [
      { id: 'air', label: 'Air', type: 'float', min: 0, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'airFreq', label: 'Airfreq', type: 'float', min: 8000, max: 20000, default: 12000, unit: 'Hz', step: 100 },
      { id: 'presence', label: 'Presence', type: 'float', min: 0, max: 6, default: 0, unit: 'dB', step: 0.1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'AirEQPluginUI', width: 320, height: 200 },
  },

  'amp_sim': {
    id: 'amp_sim',
    name: 'AmpSim',
    version: '2.0.0',
    category: 'distortion',
    type: 'insert',
    color: '#ff6600',
    processor: { kind: 'native' },
    params: [
      { id: 'drive', label: 'Drive', type: 'float', min: 0, max: 100, default: 30, unit: '%', step: 1 },
      { id: 'cabinet', label: 'Cabinet', type: 'float', min: 0, max: 5, default: 0, unit: '', step: 1 },
      { id: 'tone', label: 'Tone', type: 'float', min: 200, max: 8000, default: 3000, unit: 'Hz', step: 100 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
      { id: 'outputGain', label: 'Outputgain', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.5 },
    ],
    ui: { component: 'AmpSimPluginUI', width: 320, height: 200 },
  },

  'auto_filter': {
    id: 'auto_filter',
    name: 'AutoFilter',
    version: '2.0.0',
    category: 'filter',
    type: 'insert',
    color: '#ffaa00',
    processor: { kind: 'native' },
    params: [
      { id: 'rate', label: 'Rate', type: 'float', min: 0.01, max: 10, default: 1, unit: 'Hz', step: 0.01 },
      { id: 'depth', label: 'Depth', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'freq', label: 'Freq', type: 'float', min: 200, max: 8000, default: 1000, unit: 'Hz', step: 10 },
      { id: 'res', label: 'Res', type: 'float', min: 0, max: 20, default: 3, unit: '', step: 0.1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'AutoFilterPluginUI', width: 320, height: 200 },
  },

  'auto_pan': {
    id: 'auto_pan',
    name: 'AutoPan',
    version: '2.0.0',
    category: 'modulation',
    type: 'insert',
    color: '#ff44aa',
    processor: { kind: 'native' },
    params: [
      { id: 'rate', label: 'Rate', type: 'float', min: 0.01, max: 10, default: 1, unit: 'Hz', step: 0.01 },
      { id: 'depth', label: 'Depth', type: 'float', min: 0, max: 1, default: 0.8, unit: '', step: 0.01 },
      { id: 'wave', label: 'Wave', type: 'float', min: 0, max: 3, default: 0, unit: '', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'AutoPanPluginUI', width: 320, height: 200 },
  },

  'auto_tune': {
    id: 'auto_tune',
    name: 'AutoTune',
    version: '2.0.0',
    category: 'pitch',
    type: 'insert',
    color: '#ffcc00',
    processor: { kind: 'native' },
    params: [
      { id: 'speed', label: 'Speed', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'key', label: 'Key', type: 'float', min: 0, max: 11, default: 0, unit: '', step: 1 },
      { id: 'scale', label: 'Scale', type: 'float', min: 0, max: 6, default: 0, unit: '', step: 1 },
      { id: 'formant', label: 'Formant', type: 'float', min: 0, max: 1, default: 0, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'AutoTunePluginUI', width: 320, height: 200 },
  },

  'bass_enhancer': {
    id: 'bass_enhancer',
    name: 'BassEnhancer',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'freq', label: 'Freq', type: 'float', min: 40, max: 200, default: 80, unit: 'Hz', step: 1 },
      { id: 'drive', label: 'Drive', type: 'float', min: 0, max: 1, default: 0.4, unit: '', step: 0.01 },
      { id: 'sub', label: 'Sub', type: 'float', min: 0, max: 12, default: 4, unit: 'dB', step: 0.1 },
      { id: 'punch', label: 'Punch', type: 'float', min: 0, max: 12, default: 3, unit: 'dB', step: 0.1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'BassEnhancerPluginUI', width: 320, height: 200 },
  },

  'bit_depth': {
    id: 'bit_depth',
    name: 'BitDepth',
    version: '2.0.0',
    category: 'distortion',
    type: 'insert',
    color: '#ff6600',
    processor: { kind: 'native' },
    params: [
      { id: 'bits', label: 'Bits', type: 'float', min: 1, max: 24, default: 8, unit: 'bit', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
      { id: 'dither', label: 'Dither', type: 'float', min: 0, max: 1, default: 0.3, unit: '', step: 0.01 },
    ],
    ui: { component: 'BitDepthPluginUI', width: 320, height: 200 },
  },

  'bitcrusher': {
    id: 'bitcrusher',
    name: 'Bitcrusher',
    version: '2.0.0',
    category: 'distortion',
    type: 'insert',
    color: '#ff6600',
    processor: { kind: 'native' },
    params: [
      { id: 'bits', label: 'Bits', type: 'float', min: 1, max: 16, default: 8, unit: 'bit', step: 1 },
      { id: 'rate', label: 'Rate', type: 'float', min: 0.01, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
    ],
    ui: { component: 'BitcrusherPluginUI', width: 320, height: 200 },
  },

  'breath_gate': {
    id: 'breath_gate',
    name: 'BreathGate',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'threshold', label: 'Threshold', type: 'float', min: -80, max: 0, default: -45, unit: 'dB', step: 0.5 },
      { id: 'reduction', label: 'Reduction', type: 'float', min: -40, max: 0, default: -12, unit: 'dB', step: 0.5 },
      { id: 'attack', label: 'Attack', type: 'float', min: 0.1, max: 20, default: 2, unit: 'ms', step: 0.1 },
      { id: 'release', label: 'Release', type: 'float', min: 10, max: 500, default: 150, unit: 'ms', step: 5 },
    ],
    ui: { component: 'BreathGatePluginUI', width: 320, height: 200 },
  },

  'brickwall_limiter': {
    id: 'brickwall_limiter',
    name: 'BrickwallLimiter',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'ceiling', label: 'Ceiling', type: 'float', min: -6, max: 0, default: -0.3, unit: 'dBTP', step: 0.1 },
      { id: 'lookahead', label: 'Lookahead', type: 'float', min: 0, max: 20, default: 5, unit: 'ms', step: 0.1 },
      { id: 'release', label: 'Release', type: 'float', min: 10, max: 2000, default: 100, unit: 'ms', step: 5 },
      { id: 'outputGain', label: 'Outputgain', type: 'float', min: -12, max: 0, default: 0, unit: 'dB', step: 0.1 },
    ],
    ui: { component: 'BrickwallLimiterPluginUI', width: 320, height: 200 },
  },

  'cassette': {
    id: 'cassette',
    name: 'Cassette',
    version: '2.0.0',
    category: 'distortion',
    type: 'insert',
    color: '#ff6600',
    processor: { kind: 'native' },
    params: [
      { id: 'drive', label: 'Drive', type: 'float', min: 0, max: 1, default: 0.4, unit: '', step: 0.01 },
      { id: 'noise', label: 'Noise', type: 'float', min: 0, max: 0.2, default: 0.02, unit: '', step: 0.001 },
      { id: 'hfLoss', label: 'Hfloss', type: 'float', min: 0, max: 1, default: 0.3, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'CassettePluginUI', width: 320, height: 200 },
  },

  'chamber_reverb': {
    id: 'chamber_reverb',
    name: 'ChamberReverb',
    version: '2.0.0',
    category: 'reverb',
    type: 'insert',
    color: '#7744ff',
    processor: { kind: 'native' },
    params: [
      { id: 'decay', label: 'Decay', type: 'float', min: 0.5, max: 8, default: 2.5, unit: 's', step: 0.1 },
      { id: 'preDelay', label: 'Predelay', type: 'float', min: 0, max: 100, default: 15, unit: 'ms', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 25, unit: '%', step: 1 },
      { id: 'damping', label: 'Damping', type: 'float', min: 1000, max: 20000, default: 6000, unit: 'Hz', step: 100 },
      { id: 'diffusion', label: 'Diffusion', type: 'float', min: 0, max: 1, default: 0.8, unit: '', step: 0.01 },
    ],
    ui: { component: 'ChamberReverbPluginUI', width: 320, height: 200 },
  },

  'channel_strip': {
    id: 'channel_strip',
    name: 'ChannelStrip',
    version: '2.0.0',
    category: 'utility',
    type: 'insert',
    color: '#888888',
    processor: { kind: 'native' },
    params: [
      { id: 'inputGain', label: 'Inputgain', type: 'float', min: -24, max: 24, default: 0, unit: 'dB', step: 0.5 },
      { id: 'hpf', label: 'Hpf', type: 'float', min: 0, max: 500, default: 0, unit: 'Hz', step: 5 },
      { id: 'lpf', label: 'Lpf', type: 'float', min: 2000, max: 20000, default: 20000, unit: 'Hz', step: 100 },
      { id: 'phase', label: 'Phase', type: 'float', min: 0, max: 1, default: 0, unit: '', step: 1 },
      { id: 'outputGain', label: 'Outputgain', type: 'float', min: -24, max: 24, default: 0, unit: 'dB', step: 0.5 },
    ],
    ui: { component: 'ChannelStripPluginUI', width: 320, height: 200 },
  },

  'choir': {
    id: 'choir',
    name: 'Choir',
    version: '2.0.0',
    category: 'modulation',
    type: 'insert',
    color: '#ff44aa',
    processor: { kind: 'native' },
    params: [
      { id: 'voices', label: 'Voices', type: 'float', min: 2, max: 8, default: 4, unit: '', step: 1 },
      { id: 'spread', label: 'Spread', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'detune', label: 'Detune', type: 'float', min: 0, max: 50, default: 15, unit: '¢', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
    ],
    ui: { component: 'ChoirPluginUI', width: 320, height: 200 },
  },

  'chorus': {
    id: 'chorus',
    name: 'Chorus',
    version: '2.0.0',
    category: 'modulation',
    type: 'insert',
    color: '#ff44aa',
    processor: { kind: 'native' },
    params: [
      { id: 'rate', label: 'Rate', type: 'float', min: 0.01, max: 10, default: 1.5, unit: 'Hz', step: 0.01 },
      { id: 'depth', label: 'Depth', type: 'float', min: 0, max: 0.02, default: 0.003, unit: '', step: 0.0001 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
      { id: 'feedback', label: 'Feedback', type: 'float', min: 0, max: 0.9, default: 0.2, unit: '', step: 0.01 },
    ],
    ui: { component: 'ChorusPluginUI', width: 320, height: 200 },
  },

  'comb_filter': {
    id: 'comb_filter',
    name: 'CombFilter',
    version: '2.0.0',
    category: 'filter',
    type: 'insert',
    color: '#ffaa00',
    processor: { kind: 'native' },
    params: [
      { id: 'freq', label: 'Freq', type: 'float', min: 20, max: 2000, default: 100, unit: 'Hz', step: 1 },
      { id: 'feedback', label: 'Feedback', type: 'float', min: 0, max: 0.98, default: 0.7, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
    ],
    ui: { component: 'CombFilterPluginUI', width: 320, height: 200 },
  },

  'compressor': {
    id: 'compressor',
    name: 'Compressor',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'threshold', label: 'Threshold', type: 'float', min: -60, max: 0, default: -18, unit: 'dB', step: 0.5 },
      { id: 'ratio', label: 'Ratio', type: 'float', min: 1, max: 20, default: 4, unit: ':1', step: 0.1 },
      { id: 'attack', label: 'Attack', type: 'float', min: 0.1, max: 200, default: 10, unit: 'ms', step: 0.1 },
      { id: 'release', label: 'Release', type: 'float', min: 10, max: 2000, default: 150, unit: 'ms', step: 5 },
      { id: 'knee', label: 'Knee', type: 'float', min: 0, max: 30, default: 6, unit: 'dB', step: 0.5 },
      { id: 'makeup', label: 'Makeup', type: 'float', min: 0, max: 24, default: 0, unit: 'dB', step: 0.5 },
    ],
    ui: { component: 'CompressorPluginUI', width: 320, height: 200 },
  },

  'convolution_shaper': {
    id: 'convolution_shaper',
    name: 'ConvolutionShaper',
    version: '2.0.0',
    category: 'distortion',
    type: 'insert',
    color: '#ff6600',
    processor: { kind: 'native' },
    params: [
      { id: 'drive', label: 'Drive', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
      { id: 'tone', label: 'Tone', type: 'float', min: 200, max: 8000, default: 2000, unit: 'Hz', step: 100 },
    ],
    ui: { component: 'ConvolutionShaperPluginUI', width: 320, height: 200 },
  },

  'd_c_filter': {
    id: 'd_c_filter',
    name: 'DCFilter',
    version: '2.0.0',
    category: 'utility',
    type: 'insert',
    color: '#888888',
    processor: { kind: 'native' },
    params: [
      { id: 'freq', label: 'Freq', type: 'float', min: 1, max: 30, default: 5, unit: 'Hz', step: 0.5 },
      { id: 'slope', label: 'Slope', type: 'float', min: 6, max: 48, default: 12, unit: 'dB/oct', step: 6 },
    ],
    ui: { component: 'DCFilterPluginUI', width: 320, height: 200 },
  },

  'de_esser': {
    id: 'de_esser',
    name: 'DeEsser',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'freq', label: 'Freq', type: 'float', min: 2000, max: 16000, default: 6500, unit: 'Hz', step: 100 },
      { id: 'threshold', label: 'Threshold', type: 'float', min: -40, max: 0, default: -25, unit: 'dB', step: 0.5 },
      { id: 'ratio', label: 'Ratio', type: 'float', min: 1, max: 20, default: 6, unit: ':1', step: 0.5 },
      { id: 'speed', label: 'Speed', type: 'float', min: 0, max: 1, default: 0.3, unit: '', step: 0.01 },
    ],
    ui: { component: 'DeEsserPluginUI', width: 320, height: 200 },
  },

  'delay': {
    id: 'delay',
    name: 'Delay',
    version: '2.0.0',
    category: 'delay',
    type: 'insert',
    color: '#00aaff',
    processor: { kind: 'native' },
    params: [
      { id: 'time', label: 'Time', type: 'float', min: 10, max: 2000, default: 375, unit: 'ms', step: 1 },
      { id: 'feedback', label: 'Feedback', type: 'float', min: 0, max: 95, default: 40, unit: '%', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 25, unit: '%', step: 1 },
      { id: 'filter', label: 'Filter', type: 'float', min: 200, max: 20000, default: 8000, unit: 'Hz', step: 100 },
    ],
    ui: { component: 'DelayPluginUI', width: 320, height: 200 },
  },

  'dotted_eighth_delay': {
    id: 'dotted_eighth_delay',
    name: 'DottedEighthDelay',
    version: '2.0.0',
    category: 'delay',
    type: 'insert',
    color: '#00aaff',
    processor: { kind: 'native' },
    params: [
      { id: 'bpm', label: 'Bpm', type: 'float', min: 60, max: 200, default: 120, unit: 'BPM', step: 1 },
      { id: 'feedback', label: 'Feedback', type: 'float', min: 0, max: 95, default: 35, unit: '%', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 25, unit: '%', step: 1 },
      { id: 'filter', label: 'Filter', type: 'float', min: 200, max: 20000, default: 8000, unit: 'Hz', step: 100 },
    ],
    ui: { component: 'DottedEighthDelayPluginUI', width: 320, height: 200 },
  },

  'drum_bus': {
    id: 'drum_bus',
    name: 'DrumBus',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'punch', label: 'Punch', type: 'float', min: 0, max: 12, default: 4, unit: 'dB', step: 0.1 },
      { id: 'compress', label: 'Compress', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'transient', label: 'Transient', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'DrumBusPluginUI', width: 320, height: 200 },
  },

  'dust_scratch': {
    id: 'dust_scratch',
    name: 'DustScratch',
    version: '2.0.0',
    category: 'distortion',
    type: 'insert',
    color: '#ff6600',
    processor: { kind: 'native' },
    params: [
      { id: 'dust', label: 'Dust', type: 'float', min: 0, max: 1, default: 0.2, unit: '', step: 0.01 },
      { id: 'scratch', label: 'Scratch', type: 'float', min: 0, max: 1, default: 0.1, unit: '', step: 0.01 },
      { id: 'crackle', label: 'Crackle', type: 'float', min: 0, max: 1, default: 0.15, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'DustScratchPluginUI', width: 320, height: 200 },
  },

  'dynamic_e_q': {
    id: 'dynamic_e_q',
    name: 'DynamicEQ',
    version: '2.0.0',
    category: 'eq',
    type: 'insert',
    color: '#5ac8fa',
    processor: { kind: 'native' },
    params: [
      { id: 'freq', label: 'Freq', type: 'float', min: 20, max: 20000, default: 1000, unit: 'Hz', step: 1 },
      { id: 'gain', label: 'Gain', type: 'float', min: -18, max: 18, default: 0, unit: 'dB', step: 0.1 },
      { id: 'q', label: 'Q', type: 'float', min: 0.1, max: 10, default: 1, unit: '', step: 0.1 },
      { id: 'threshold', label: 'Threshold', type: 'float', min: -40, max: 0, default: -18, unit: 'dB', step: 0.5 },
      { id: 'ratio', label: 'Ratio', type: 'float', min: 1, max: 20, default: 3, unit: ':1', step: 0.5 },
    ],
    ui: { component: 'DynamicEQPluginUI', width: 320, height: 200 },
  },

  'e_q3_band': {
    id: 'e_q3_band',
    name: 'EQ3Band',
    version: '2.0.0',
    category: 'eq',
    type: 'insert',
    color: '#5ac8fa',
    processor: { kind: 'native' },
    params: [
      { id: 'lowGain', label: 'Lowgain', type: 'float', min: -18, max: 18, default: 0, unit: 'dB', step: 0.1 },
      { id: 'midGain', label: 'Midgain', type: 'float', min: -18, max: 18, default: 0, unit: 'dB', step: 0.1 },
      { id: 'highGain', label: 'Highgain', type: 'float', min: -18, max: 18, default: 0, unit: 'dB', step: 0.1 },
      { id: 'lowFreq', label: 'Lowfreq', type: 'float', min: 30, max: 500, default: 150, unit: 'Hz', step: 1 },
      { id: 'highFreq', label: 'Highfreq', type: 'float', min: 2000, max: 20000, default: 8000, unit: 'Hz', step: 100 },
    ],
    ui: { component: 'EQ3BandPluginUI', width: 320, height: 200 },
  },

  'envelope_filter': {
    id: 'envelope_filter',
    name: 'EnvelopeFilter',
    version: '2.0.0',
    category: 'filter',
    type: 'insert',
    color: '#ffaa00',
    processor: { kind: 'native' },
    params: [
      { id: 'attack', label: 'Attack', type: 'float', min: 0.1, max: 200, default: 10, unit: 'ms', step: 0.1 },
      { id: 'release', label: 'Release', type: 'float', min: 10, max: 1000, default: 100, unit: 'ms', step: 5 },
      { id: 'freq', label: 'Freq', type: 'float', min: 200, max: 8000, default: 800, unit: 'Hz', step: 10 },
      { id: 'depth', label: 'Depth', type: 'float', min: 0, max: 1, default: 0.8, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'EnvelopeFilterPluginUI', width: 320, height: 200 },
  },

  'expander': {
    id: 'expander',
    name: 'Expander',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'threshold', label: 'Threshold', type: 'float', min: -80, max: 0, default: -40, unit: 'dB', step: 0.5 },
      { id: 'ratio', label: 'Ratio', type: 'float', min: 1, max: 10, default: 2, unit: ':1', step: 0.1 },
      { id: 'attack', label: 'Attack', type: 'float', min: 0.1, max: 200, default: 10, unit: 'ms', step: 0.1 },
      { id: 'release', label: 'Release', type: 'float', min: 10, max: 1000, default: 100, unit: 'ms', step: 5 },
    ],
    ui: { component: 'ExpanderPluginUI', width: 320, height: 200 },
  },

  'f_e_t_comp': {
    id: 'f_e_t_comp',
    name: 'FETComp',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'threshold', label: 'Threshold', type: 'float', min: -40, max: 0, default: -15, unit: 'dB', step: 0.5 },
      { id: 'ratio', label: 'Ratio', type: 'float', min: 1, max: 20, default: 8, unit: ':1', step: 0.5 },
      { id: 'attack', label: 'Attack', type: 'float', min: 0.1, max: 10, default: 0.5, unit: 'ms', step: 0.1 },
      { id: 'release', label: 'Release', type: 'float', min: 10, max: 1200, default: 50, unit: 'ms', step: 5 },
      { id: 'inputGain', label: 'Inputgain', type: 'float', min: 0, max: 4, default: 1, unit: '', step: 0.01 },
      { id: 'outputGain', label: 'Outputgain', type: 'float', min: 0, max: 4, default: 1, unit: '', step: 0.01 },
    ],
    ui: { component: 'FETCompPluginUI', width: 320, height: 200 },
  },

  'flanger': {
    id: 'flanger',
    name: 'Flanger',
    version: '2.0.0',
    category: 'modulation',
    type: 'insert',
    color: '#ff44aa',
    processor: { kind: 'native' },
    params: [
      { id: 'rate', label: 'Rate', type: 'float', min: 0.01, max: 10, default: 0.3, unit: 'Hz', step: 0.01 },
      { id: 'depth', label: 'Depth', type: 'float', min: 0, max: 0.01, default: 0.003, unit: '', step: 0.0001 },
      { id: 'feedback', label: 'Feedback', type: 'float', min: 0, max: 0.95, default: 0.5, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
    ],
    ui: { component: 'FlangerPluginUI', width: 320, height: 200 },
  },

  'frequency_shifter': {
    id: 'frequency_shifter',
    name: 'FrequencyShifter',
    version: '2.0.0',
    category: 'modulation',
    type: 'insert',
    color: '#ff44aa',
    processor: { kind: 'native' },
    params: [
      { id: 'shift', label: 'Shift', type: 'float', min: -1000, max: 1000, default: 0, unit: 'Hz', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'FrequencyShifterPluginUI', width: 320, height: 200 },
  },

  'fuzz': {
    id: 'fuzz',
    name: 'Fuzz',
    version: '2.0.0',
    category: 'distortion',
    type: 'insert',
    color: '#ff6600',
    processor: { kind: 'native' },
    params: [
      { id: 'drive', label: 'Drive', type: 'float', min: 0, max: 1, default: 0.7, unit: '', step: 0.01 },
      { id: 'tone', label: 'Tone', type: 'float', min: 200, max: 8000, default: 2000, unit: 'Hz', step: 100 },
      { id: 'bias', label: 'Bias', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
      { id: 'outputGain', label: 'Outputgain', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.5 },
    ],
    ui: { component: 'FuzzPluginUI', width: 320, height: 200 },
  },

  'gain': {
    id: 'gain',
    name: 'Gain',
    version: '2.0.0',
    category: 'utility',
    type: 'insert',
    color: '#888888',
    processor: { kind: 'native' },
    params: [
      { id: 'gainDb', label: 'Gaindb', type: 'float', min: -48, max: 24, default: 0, unit: 'dB', step: 0.1 },
      { id: 'phase', label: 'Phase', type: 'float', min: 0, max: 1, default: 0, unit: '', step: 1 },
    ],
    ui: { component: 'GainPluginUI', width: 320, height: 200 },
  },

  'gate': {
    id: 'gate',
    name: 'Gate',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'threshold', label: 'Threshold', type: 'float', min: -80, max: 0, default: -40, unit: 'dB', step: 0.5 },
      { id: 'attack', label: 'Attack', type: 'float', min: 0.1, max: 50, default: 1, unit: 'ms', step: 0.1 },
      { id: 'hold', label: 'Hold', type: 'float', min: 0, max: 2000, default: 50, unit: 'ms', step: 1 },
      { id: 'release', label: 'Release', type: 'float', min: 10, max: 4000, default: 200, unit: 'ms', step: 5 },
      { id: 'range', label: 'Range', type: 'float', min: -80, max: 0, default: -80, unit: 'dB', step: 1 },
    ],
    ui: { component: 'GatePluginUI', width: 320, height: 200 },
  },

  'gated_reverb': {
    id: 'gated_reverb',
    name: 'GatedReverb',
    version: '2.0.0',
    category: 'reverb',
    type: 'insert',
    color: '#7744ff',
    processor: { kind: 'native' },
    params: [
      { id: 'decay', label: 'Decay', type: 'float', min: 0.1, max: 2, default: 0.5, unit: 's', step: 0.05 },
      { id: 'gateTime', label: 'Gatetime', type: 'float', min: 10, max: 500, default: 200, unit: 'ms', step: 5 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 35, unit: '%', step: 1 },
      { id: 'preDelay', label: 'Predelay', type: 'float', min: 0, max: 50, default: 5, unit: 'ms', step: 1 },
    ],
    ui: { component: 'GatedReverbPluginUI', width: 320, height: 200 },
  },

  'granular_freeze': {
    id: 'granular_freeze',
    name: 'GranularFreeze',
    version: '2.0.0',
    category: 'creative',
    type: 'insert',
    color: '#aa44ff',
    processor: { kind: 'native' },
    params: [
      { id: 'grainSize', label: 'Grainsize', type: 'float', min: 10, max: 500, default: 80, unit: 'ms', step: 5 },
      { id: 'density', label: 'Density', type: 'float', min: 0.1, max: 1, default: 0.7, unit: '', step: 0.01 },
      { id: 'pitch', label: 'Pitch', type: 'float', min: -24, max: 24, default: 0, unit: 'st', step: 0.5 },
      { id: 'spread', label: 'Spread', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 80, unit: '%', step: 1 },
    ],
    ui: { component: 'GranularFreezePluginUI', width: 320, height: 200 },
  },

  'graphic_e_q': {
    id: 'graphic_e_q',
    name: 'GraphicEQ',
    version: '2.0.0',
    category: 'eq',
    type: 'insert',
    color: '#5ac8fa',
    processor: { kind: 'native' },
    params: [
      { id: 'b63', label: 'B63', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'b125', label: 'B125', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'b250', label: 'B250', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'b500', label: 'B500', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'b1k', label: 'B1K', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'b2k', label: 'B2K', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'b4k', label: 'B4K', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'b8k', label: 'B8K', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'b16k', label: 'B16K', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
    ],
    ui: { component: 'GraphicEQPluginUI', width: 320, height: 200 },
  },

  'haas_effect': {
    id: 'haas_effect',
    name: 'HaasEffect',
    version: '2.0.0',
    category: 'spatial',
    type: 'insert',
    color: '#44ffaa',
    processor: { kind: 'native' },
    params: [
      { id: 'delay', label: 'Delay', type: 'float', min: 1, max: 40, default: 15, unit: 'ms', step: 0.5 },
      { id: 'width', label: 'Width', type: 'float', min: 0, max: 1, default: 0.8, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
    ],
    ui: { component: 'HaasEffectPluginUI', width: 320, height: 200 },
  },

  'hall_reverb': {
    id: 'hall_reverb',
    name: 'HallReverb',
    version: '2.0.0',
    category: 'reverb',
    type: 'insert',
    color: '#7744ff',
    processor: { kind: 'native' },
    params: [
      { id: 'decay', label: 'Decay', type: 'float', min: 0.5, max: 12, default: 4, unit: 's', step: 0.1 },
      { id: 'preDelay', label: 'Predelay', type: 'float', min: 0, max: 150, default: 30, unit: 'ms', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 30, unit: '%', step: 1 },
      { id: 'damping', label: 'Damping', type: 'float', min: 1000, max: 20000, default: 6000, unit: 'Hz', step: 100 },
      { id: 'diffusion', label: 'Diffusion', type: 'float', min: 0, max: 1, default: 0.85, unit: '', step: 0.01 },
      { id: 'earlyLevel', label: 'Earlylevel', type: 'float', min: 0, max: 1, default: 0.7, unit: '', step: 0.01 },
    ],
    ui: { component: 'HallReverbPluginUI', width: 320, height: 200 },
  },

  'harmonic_exciter': {
    id: 'harmonic_exciter',
    name: 'HarmonicExciter',
    version: '2.0.0',
    category: 'distortion',
    type: 'insert',
    color: '#ff6600',
    processor: { kind: 'native' },
    params: [
      { id: 'freq', label: 'Freq', type: 'float', min: 500, max: 12000, default: 3000, unit: 'Hz', step: 100 },
      { id: 'drive', label: 'Drive', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'even', label: 'Even', type: 'float', min: 0, max: 1, default: 0.6, unit: '', step: 0.01 },
      { id: 'odd', label: 'Odd', type: 'float', min: 0, max: 1, default: 0.3, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 30, unit: '%', step: 1 },
    ],
    ui: { component: 'HarmonicExciterPluginUI', width: 320, height: 200 },
  },

  'harmonizer': {
    id: 'harmonizer',
    name: 'Harmonizer',
    version: '2.0.0',
    category: 'pitch',
    type: 'insert',
    color: '#ffcc00',
    processor: { kind: 'native' },
    params: [
      { id: 'shift1', label: 'Shift1', type: 'float', min: -24, max: 24, default: -5, unit: 'st', step: 1 },
      { id: 'shift2', label: 'Shift2', type: 'float', min: -24, max: 24, default: 3, unit: 'st', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
      { id: 'formant', label: 'Formant', type: 'float', min: 0, max: 1, default: 0, unit: '', step: 0.01 },
    ],
    ui: { component: 'HarmonizerPluginUI', width: 320, height: 200 },
  },

  'hi_hat_shimmer': {
    id: 'hi_hat_shimmer',
    name: 'HiHatShimmer',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'freq', label: 'Freq', type: 'float', min: 8000, max: 20000, default: 12000, unit: 'Hz', step: 100 },
      { id: 'drive', label: 'Drive', type: 'float', min: 0, max: 1, default: 0.3, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 30, unit: '%', step: 1 },
    ],
    ui: { component: 'HiHatShimmerPluginUI', width: 320, height: 200 },
  },

  'kick_enhancer': {
    id: 'kick_enhancer',
    name: 'KickEnhancer',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'punch', label: 'Punch', type: 'float', min: 0, max: 12, default: 4, unit: 'dB', step: 0.1 },
      { id: 'sub', label: 'Sub', type: 'float', min: 0, max: 12, default: 3, unit: 'dB', step: 0.1 },
      { id: 'click', label: 'Click', type: 'float', min: 0, max: 12, default: 2, unit: 'dB', step: 0.1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'KickEnhancerPluginUI', width: 320, height: 200 },
  },

  'limiter': {
    id: 'limiter',
    name: 'Limiter',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'ceiling', label: 'Ceiling', type: 'float', min: -12, max: 0, default: -0.3, unit: 'dB', step: 0.1 },
      { id: 'release', label: 'Release', type: 'float', min: 1, max: 500, default: 50, unit: 'ms', step: 1 },
      { id: 'lookahead', label: 'Lookahead', type: 'float', min: 0, max: 20, default: 5, unit: 'ms', step: 0.1 },
    ],
    ui: { component: 'LimiterPluginUI', width: 320, height: 200 },
  },

  'linear_phase_e_q': {
    id: 'linear_phase_e_q',
    name: 'LinearPhaseEQ',
    version: '2.0.0',
    category: 'eq',
    type: 'insert',
    color: '#5ac8fa',
    processor: { kind: 'native' },
    params: [
      { id: 'lowGain', label: 'Lowgain', type: 'float', min: -18, max: 18, default: 0, unit: 'dB', step: 0.1 },
      { id: 'lowFreq', label: 'Lowfreq', type: 'float', min: 20, max: 500, default: 100, unit: 'Hz', step: 1 },
      { id: 'midGain', label: 'Midgain', type: 'float', min: -18, max: 18, default: 0, unit: 'dB', step: 0.1 },
      { id: 'midFreq', label: 'Midfreq', type: 'float', min: 200, max: 8000, default: 1000, unit: 'Hz', step: 1 },
      { id: 'highGain', label: 'Highgain', type: 'float', min: -18, max: 18, default: 0, unit: 'dB', step: 0.1 },
      { id: 'highFreq', label: 'Highfreq', type: 'float', min: 2000, max: 20000, default: 8000, unit: 'Hz', step: 100 },
    ],
    ui: { component: 'LinearPhaseEQPluginUI', width: 320, height: 200 },
  },

  'looper': {
    id: 'looper',
    name: 'Looper',
    version: '2.0.0',
    category: 'creative',
    type: 'insert',
    color: '#aa44ff',
    processor: { kind: 'native' },
    params: [
      { id: 'length', label: 'Length', type: 'float', min: 0.25, max: 32, default: 4, unit: 'bars', step: 0.25 },
      { id: 'speed', label: 'Speed', type: 'float', min: 0.25, max: 2, default: 1, unit: 'x', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
      { id: 'feedback', label: 'Feedback', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'LooperPluginUI', width: 320, height: 200 },
  },

  'loudness_maximizer': {
    id: 'loudness_maximizer',
    name: 'LoudnessMaximizer',
    version: '2.0.0',
    category: 'mastering',
    type: 'insert',
    color: '#ff2244',
    processor: { kind: 'native' },
    params: [
      { id: 'ceiling', label: 'Ceiling', type: 'float', min: -3, max: 0, default: -0.3, unit: 'dBTP', step: 0.1 },
      { id: 'loudness', label: 'Loudness', type: 'float', min: -24, max: 0, default: -14, unit: 'LUFS', step: 0.5 },
      { id: 'transient', label: 'Transient', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
    ],
    ui: { component: 'LoudnessMaximizerPluginUI', width: 320, height: 200 },
  },

  'mastering_e_q': {
    id: 'mastering_e_q',
    name: 'MasteringEQ',
    version: '2.0.0',
    category: 'eq',
    type: 'insert',
    color: '#5ac8fa',
    processor: { kind: 'native' },
    params: [
      { id: 'sub', label: 'Sub', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'low', label: 'Low', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'lowMid', label: 'Lowmid', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'highMid', label: 'Highmid', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'high', label: 'High', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'air', label: 'Air', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
    ],
    ui: { component: 'MasteringEQPluginUI', width: 320, height: 200 },
  },

  'mid_side_balance': {
    id: 'mid_side_balance',
    name: 'MidSideBalance',
    version: '2.0.0',
    category: 'spatial',
    type: 'insert',
    color: '#44ffaa',
    processor: { kind: 'native' },
    params: [
      { id: 'midGain', label: 'Midgain', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'sideGain', label: 'Sidegain', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'width', label: 'Width', type: 'float', min: 0, max: 200, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'MidSideBalancePluginUI', width: 320, height: 200 },
  },

  'mid_side_e_q': {
    id: 'mid_side_e_q',
    name: 'MidSideEQ',
    version: '2.0.0',
    category: 'eq',
    type: 'insert',
    color: '#5ac8fa',
    processor: { kind: 'native' },
    params: [
      { id: 'midLow', label: 'Midlow', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'midHigh', label: 'Midhigh', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'sideLow', label: 'Sidelow', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'sideHigh', label: 'Sidehigh', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
    ],
    ui: { component: 'MidSideEQPluginUI', width: 320, height: 200 },
  },

  'mid_side_processor': {
    id: 'mid_side_processor',
    name: 'MidSideProcessor',
    version: '2.0.0',
    category: 'spatial',
    type: 'insert',
    color: '#44ffaa',
    processor: { kind: 'native' },
    params: [
      { id: 'encode', label: 'Encode', type: 'float', min: 0, max: 1, default: 1, unit: '', step: 1 },
      { id: 'midGain', label: 'Midgain', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'sideGain', label: 'Sidegain', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
    ],
    ui: { component: 'MidSideProcessorPluginUI', width: 320, height: 200 },
  },

  'mono_maker': {
    id: 'mono_maker',
    name: 'MonoMaker',
    version: '2.0.0',
    category: 'utility',
    type: 'insert',
    color: '#888888',
    processor: { kind: 'native' },
    params: [
      { id: 'freq', label: 'Freq', type: 'float', min: 20, max: 300, default: 100, unit: 'Hz', step: 5 },
      { id: 'phase', label: 'Phase', type: 'float', min: 0, max: 1, default: 0, unit: '', step: 1 },
    ],
    ui: { component: 'MonoMakerPluginUI', width: 320, height: 200 },
  },

  'multiband_comp': {
    id: 'multiband_comp',
    name: 'MultibandComp',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'xover1', label: 'Xover1', type: 'float', min: 80, max: 500, default: 200, unit: 'Hz', step: 5 },
      { id: 'xover2', label: 'Xover2', type: 'float', min: 500, max: 5000, default: 2000, unit: 'Hz', step: 10 },
      { id: 'xover3', label: 'Xover3', type: 'float', min: 2000, max: 16000, default: 8000, unit: 'Hz', step: 100 },
      { id: 'compLow', label: 'Complow', type: 'float', min: 0, max: 1, default: 0.3, unit: '', step: 0.01 },
      { id: 'compMid', label: 'Compmid', type: 'float', min: 0, max: 1, default: 0.3, unit: '', step: 0.01 },
      { id: 'compHigh', label: 'Comphigh', type: 'float', min: 0, max: 1, default: 0.3, unit: '', step: 0.01 },
    ],
    ui: { component: 'MultibandCompPluginUI', width: 320, height: 200 },
  },

  'multitap_delay': {
    id: 'multitap_delay',
    name: 'MultitapDelay',
    version: '2.0.0',
    category: 'delay',
    type: 'insert',
    color: '#00aaff',
    processor: { kind: 'native' },
    params: [
      { id: 'tap1', label: 'Tap1', type: 'float', min: 50, max: 500, default: 125, unit: 'ms', step: 1 },
      { id: 'tap2', label: 'Tap2', type: 'float', min: 100, max: 1000, default: 250, unit: 'ms', step: 1 },
      { id: 'tap3', label: 'Tap3', type: 'float', min: 200, max: 2000, default: 500, unit: 'ms', step: 1 },
      { id: 'feedback', label: 'Feedback', type: 'float', min: 0, max: 0.9, default: 0.4, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 30, unit: '%', step: 1 },
    ],
    ui: { component: 'MultitapDelayPluginUI', width: 320, height: 200 },
  },

  'notch_e_q': {
    id: 'notch_e_q',
    name: 'NotchEQ',
    version: '2.0.0',
    category: 'eq',
    type: 'insert',
    color: '#5ac8fa',
    processor: { kind: 'native' },
    params: [
      { id: 'freq', label: 'Freq', type: 'float', min: 20, max: 20000, default: 1000, unit: 'Hz', step: 1 },
      { id: 'q', label: 'Q', type: 'float', min: 1, max: 30, default: 10, unit: '', step: 0.1 },
      { id: 'gain', label: 'Gain', type: 'float', min: -30, max: 0, default: -12, unit: 'dB', step: 0.1 },
    ],
    ui: { component: 'NotchEQPluginUI', width: 320, height: 200 },
  },

  'octaver': {
    id: 'octaver',
    name: 'Octaver',
    version: '2.0.0',
    category: 'pitch',
    type: 'insert',
    color: '#ffcc00',
    processor: { kind: 'native' },
    params: [
      { id: 'oct1', label: 'Oct1', type: 'float', min: -2, max: 0, default: -1, unit: 'oct', step: 1 },
      { id: 'oct2', label: 'Oct2', type: 'float', min: 0, max: 2, default: 1, unit: 'oct', step: 1 },
      { id: 'mix1', label: 'Mix1', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
      { id: 'mix2', label: 'Mix2', type: 'float', min: 0, max: 100, default: 30, unit: '%', step: 1 },
      { id: 'dry', label: 'Dry', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'OctaverPluginUI', width: 320, height: 200 },
  },

  'optical_comp': {
    id: 'optical_comp',
    name: 'OpticalComp',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'peakReduction', label: 'Peakreduction', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
      { id: 'gainControl', label: 'Gaincontrol', type: 'float', min: 0, max: 40, default: 0, unit: 'dB', step: 0.5 },
      { id: 'tubeSat', label: 'Tubesat', type: 'float', min: 0, max: 1, default: 0.4, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'OpticalCompPluginUI', width: 320, height: 200 },
  },

  'overdrive': {
    id: 'overdrive',
    name: 'Overdrive',
    version: '2.0.0',
    category: 'distortion',
    type: 'insert',
    color: '#ff6600',
    processor: { kind: 'native' },
    params: [
      { id: 'drive', label: 'Drive', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'tone', label: 'Tone', type: 'float', min: 200, max: 8000, default: 2000, unit: 'Hz', step: 100 },
      { id: 'level', label: 'Level', type: 'float', min: 0, max: 1, default: 0.7, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'OverdrivePluginUI', width: 320, height: 200 },
  },

  'parallel_comp': {
    id: 'parallel_comp',
    name: 'ParallelComp',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'threshold', label: 'Threshold', type: 'float', min: -50, max: 0, default: -25, unit: 'dB', step: 0.5 },
      { id: 'ratio', label: 'Ratio', type: 'float', min: 2, max: 40, default: 10, unit: ':1', step: 0.5 },
      { id: 'crush', label: 'Crush', type: 'float', min: 0, max: 1, default: 0.7, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
      { id: 'wetGain', label: 'Wetgain', type: 'float', min: 0, max: 4, default: 1, unit: '', step: 0.01 },
    ],
    ui: { component: 'ParallelCompPluginUI', width: 320, height: 200 },
  },

  'phase_flip': {
    id: 'phase_flip',
    name: 'PhaseFlip',
    version: '2.0.0',
    category: 'utility',
    type: 'insert',
    color: '#888888',
    processor: { kind: 'native' },
    params: [
      { id: 'left', label: 'Left', type: 'float', min: 0, max: 1, default: 0, unit: '', step: 1 },
      { id: 'right', label: 'Right', type: 'float', min: 0, max: 1, default: 0, unit: '', step: 1 },
    ],
    ui: { component: 'PhaseFlipPluginUI', width: 320, height: 200 },
  },

  'phaser': {
    id: 'phaser',
    name: 'Phaser',
    version: '2.0.0',
    category: 'modulation',
    type: 'insert',
    color: '#ff44aa',
    processor: { kind: 'native' },
    params: [
      { id: 'rate', label: 'Rate', type: 'float', min: 0.01, max: 10, default: 0.5, unit: 'Hz', step: 0.01 },
      { id: 'depth', label: 'Depth', type: 'float', min: 0, max: 1000, default: 500, unit: 'Hz', step: 10 },
      { id: 'resonance', label: 'Resonance', type: 'float', min: 0, max: 20, default: 3, unit: '', step: 0.1 },
      { id: 'stages', label: 'Stages', type: 'float', min: 2, max: 12, default: 6, unit: '', step: 2 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
    ],
    ui: { component: 'PhaserPluginUI', width: 320, height: 200 },
  },

  'phone': {
    id: 'phone',
    name: 'Phone',
    version: '2.0.0',
    category: 'filter',
    type: 'insert',
    color: '#ffaa00',
    processor: { kind: 'native' },
    params: [
      { id: 'preset', label: 'Preset', type: 'float', min: 0, max: 4, default: 0, unit: '', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
      { id: 'drive', label: 'Drive', type: 'float', min: 0, max: 1, default: 0.3, unit: '', step: 0.01 },
    ],
    ui: { component: 'PhonePluginUI', width: 320, height: 200 },
  },

  'ping_pong_delay': {
    id: 'ping_pong_delay',
    name: 'PingPongDelay',
    version: '2.0.0',
    category: 'delay',
    type: 'insert',
    color: '#00aaff',
    processor: { kind: 'native' },
    params: [
      { id: 'time', label: 'Time', type: 'float', min: 10, max: 2000, default: 375, unit: 'ms', step: 1 },
      { id: 'feedback', label: 'Feedback', type: 'float', min: 0, max: 0.9, default: 0.4, unit: '', step: 0.01 },
      { id: 'spread', label: 'Spread', type: 'float', min: 0, max: 1, default: 1, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 30, unit: '%', step: 1 },
    ],
    ui: { component: 'PingPongDelayPluginUI', width: 320, height: 200 },
  },

  'pitch_shifter': {
    id: 'pitch_shifter',
    name: 'PitchShifter',
    version: '2.0.0',
    category: 'pitch',
    type: 'insert',
    color: '#ffcc00',
    processor: { kind: 'native' },
    params: [
      { id: 'shift', label: 'Shift', type: 'float', min: -24, max: 24, default: 0, unit: 'st', step: 0.1 },
      { id: 'formant', label: 'Formant', type: 'float', min: 0, max: 1, default: 0, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'PitchShifterPluginUI', width: 320, height: 200 },
  },

  'plate_reverb': {
    id: 'plate_reverb',
    name: 'PlateReverb',
    version: '2.0.0',
    category: 'reverb',
    type: 'insert',
    color: '#7744ff',
    processor: { kind: 'native' },
    params: [
      { id: 'decay', label: 'Decay', type: 'float', min: 0.3, max: 8, default: 2, unit: 's', step: 0.1 },
      { id: 'brightness', label: 'Brightness', type: 'float', min: -6, max: 6, default: 2, unit: 'dB', step: 0.1 },
      { id: 'preDelay', label: 'Predelay', type: 'float', min: 0, max: 50, default: 5, unit: 'ms', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 25, unit: '%', step: 1 },
      { id: 'diffusion', label: 'Diffusion', type: 'float', min: 0, max: 1, default: 0.9, unit: '', step: 0.01 },
    ],
    ui: { component: 'PlateReverbPluginUI', width: 320, height: 200 },
  },

  'presence_e_q': {
    id: 'presence_e_q',
    name: 'PresenceEQ',
    version: '2.0.0',
    category: 'eq',
    type: 'insert',
    color: '#5ac8fa',
    processor: { kind: 'native' },
    params: [
      { id: 'presence', label: 'Presence', type: 'float', min: 0, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'freq', label: 'Freq', type: 'float', min: 1000, max: 8000, default: 3000, unit: 'Hz', step: 100 },
      { id: 'q', label: 'Q', type: 'float', min: 0.3, max: 3, default: 0.7, unit: '', step: 0.1 },
      { id: 'air', label: 'Air', type: 'float', min: 0, max: 9, default: 0, unit: 'dB', step: 0.1 },
    ],
    ui: { component: 'PresenceEQPluginUI', width: 320, height: 200 },
  },

  'radio': {
    id: 'radio',
    name: 'Radio',
    version: '2.0.0',
    category: 'filter',
    type: 'insert',
    color: '#ffaa00',
    processor: { kind: 'native' },
    params: [
      { id: 'style', label: 'Style', type: 'float', min: 0, max: 4, default: 0, unit: '', step: 1 },
      { id: 'distortion', label: 'Distortion', type: 'float', min: 0, max: 1, default: 0.2, unit: '', step: 0.01 },
      { id: 'bandwidth', label: 'Bandwidth', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'RadioPluginUI', width: 320, height: 200 },
  },

  'resonator': {
    id: 'resonator',
    name: 'Resonator',
    version: '2.0.0',
    category: 'filter',
    type: 'insert',
    color: '#ffaa00',
    processor: { kind: 'native' },
    params: [
      { id: 'freq', label: 'Freq', type: 'float', min: 40, max: 4000, default: 200, unit: 'Hz', step: 1 },
      { id: 'decay', label: 'Decay', type: 'float', min: 0.1, max: 5, default: 1, unit: 's', step: 0.1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
      { id: 'tune', label: 'Tune', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
    ],
    ui: { component: 'ResonatorPluginUI', width: 320, height: 200 },
  },

  'reverb': {
    id: 'reverb',
    name: 'Reverb',
    version: '2.0.0',
    category: 'reverb',
    type: 'insert',
    color: '#7744ff',
    processor: { kind: 'native' },
    params: [
      { id: 'decay', label: 'Decay', type: 'float', min: 0.2, max: 8, default: 2, unit: 's', step: 0.1 },
      { id: 'preDelay', label: 'Predelay', type: 'float', min: 0, max: 100, default: 10, unit: 'ms', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 25, unit: '%', step: 1 },
      { id: 'damping', label: 'Damping', type: 'float', min: 200, max: 20000, default: 8000, unit: 'Hz', step: 100 },
    ],
    ui: { component: 'ReverbPluginUI', width: 320, height: 200 },
  },

  'reverse_reverb': {
    id: 'reverse_reverb',
    name: 'ReverseReverb',
    version: '2.0.0',
    category: 'reverb',
    type: 'insert',
    color: '#7744ff',
    processor: { kind: 'native' },
    params: [
      { id: 'decay', label: 'Decay', type: 'float', min: 0.5, max: 8, default: 2, unit: 's', step: 0.1 },
      { id: 'preDelay', label: 'Predelay', type: 'float', min: 0, max: 500, default: 100, unit: 'ms', step: 5 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 30, unit: '%', step: 1 },
    ],
    ui: { component: 'ReverseReverbPluginUI', width: 320, height: 200 },
  },

  'ring_mod': {
    id: 'ring_mod',
    name: 'RingMod',
    version: '2.0.0',
    category: 'modulation',
    type: 'insert',
    color: '#ff44aa',
    processor: { kind: 'native' },
    params: [
      { id: 'freq', label: 'Freq', type: 'float', min: 1, max: 8000, default: 440, unit: 'Hz', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
      { id: 'lfoRate', label: 'Lforate', type: 'float', min: 0, max: 20, default: 0, unit: 'Hz', step: 0.01 },
    ],
    ui: { component: 'RingModPluginUI', width: 320, height: 200 },
  },

  'room_reverb': {
    id: 'room_reverb',
    name: 'RoomReverb',
    version: '2.0.0',
    category: 'reverb',
    type: 'insert',
    color: '#7744ff',
    processor: { kind: 'native' },
    params: [
      { id: 'size', label: 'Size', type: 'float', min: 0, max: 1, default: 0.3, unit: '', step: 0.01 },
      { id: 'decay', label: 'Decay', type: 'float', min: 0.1, max: 3, default: 0.8, unit: 's', step: 0.05 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 20, unit: '%', step: 1 },
      { id: 'damping', label: 'Damping', type: 'float', min: 1000, max: 20000, default: 8000, unit: 'Hz', step: 100 },
      { id: 'diffusion', label: 'Diffusion', type: 'float', min: 0, max: 1, default: 0.7, unit: '', step: 0.01 },
    ],
    ui: { component: 'RoomReverbPluginUI', width: 320, height: 200 },
  },

  'rotary': {
    id: 'rotary',
    name: 'Rotary',
    version: '2.0.0',
    category: 'modulation',
    type: 'insert',
    color: '#ff44aa',
    processor: { kind: 'native' },
    params: [
      { id: 'speed', label: 'Speed', type: 'float', min: 0, max: 1, default: 0, unit: '', step: 1 },
      { id: 'slowRate', label: 'Slowrate', type: 'float', min: 0.1, max: 2, default: 0.8, unit: 'Hz', step: 0.01 },
      { id: 'fastRate', label: 'Fastrate', type: 'float', min: 2, max: 10, default: 6.7, unit: 'Hz', step: 0.1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'RotaryPluginUI', width: 320, height: 200 },
  },

  'sample_rate_reducer': {
    id: 'sample_rate_reducer',
    name: 'SampleRateReducer',
    version: '2.0.0',
    category: 'distortion',
    type: 'insert',
    color: '#ff6600',
    processor: { kind: 'native' },
    params: [
      { id: 'rate', label: 'Rate', type: 'float', min: 1000, max: 44100, default: 22050, unit: 'Hz', step: 100 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'SampleRateReducerPluginUI', width: 320, height: 200 },
  },

  'saturation': {
    id: 'saturation',
    name: 'Saturation',
    version: '2.0.0',
    category: 'distortion',
    type: 'insert',
    color: '#ff6600',
    processor: { kind: 'native' },
    params: [
      { id: 'drive', label: 'Drive', type: 'float', min: 0, max: 100, default: 20, unit: '%', step: 1 },
      { id: 'tone', label: 'Tone', type: 'float', min: 200, max: 20000, default: 8000, unit: 'Hz', step: 100 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
      { id: 'type', label: 'Type', type: 'float', min: 0, max: 4, default: 0, unit: '', step: 1 },
    ],
    ui: { component: 'SaturationPluginUI', width: 320, height: 200 },
  },

  'shimmer_reverb': {
    id: 'shimmer_reverb',
    name: 'ShimmerReverb',
    version: '2.0.0',
    category: 'reverb',
    type: 'insert',
    color: '#7744ff',
    processor: { kind: 'native' },
    params: [
      { id: 'decay', label: 'Decay', type: 'float', min: 0.5, max: 8, default: 3, unit: 's', step: 0.1 },
      { id: 'shimmer', label: 'Shimmer', type: 'float', min: 0, max: 1, default: 0.7, unit: '', step: 0.01 },
      { id: 'pitch', label: 'Pitch', type: 'float', min: 0, max: 24, default: 12, unit: 'st', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 40, unit: '%', step: 1 },
      { id: 'feedback', label: 'Feedback', type: 'float', min: 0, max: 0.95, default: 0.7, unit: '', step: 0.01 },
    ],
    ui: { component: 'ShimmerReverbPluginUI', width: 320, height: 200 },
  },

  'slapback_delay': {
    id: 'slapback_delay',
    name: 'SlapbackDelay',
    version: '2.0.0',
    category: 'delay',
    type: 'insert',
    color: '#00aaff',
    processor: { kind: 'native' },
    params: [
      { id: 'time', label: 'Time', type: 'float', min: 10, max: 120, default: 60, unit: 'ms', step: 1 },
      { id: 'feedback', label: 'Feedback', type: 'float', min: 0, max: 0.5, default: 0.1, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 30, unit: '%', step: 1 },
    ],
    ui: { component: 'SlapbackDelayPluginUI', width: 320, height: 200 },
  },

  'snare_enhancer': {
    id: 'snare_enhancer',
    name: 'SnareEnhancer',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'crack', label: 'Crack', type: 'float', min: 0, max: 12, default: 3, unit: 'dB', step: 0.1 },
      { id: 'snap', label: 'Snap', type: 'float', min: 0, max: 12, default: 3, unit: 'dB', step: 0.1 },
      { id: 'body', label: 'Body', type: 'float', min: 0, max: 12, default: 2, unit: 'dB', step: 0.1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'SnareEnhancerPluginUI', width: 320, height: 200 },
  },

  'spectral_gate': {
    id: 'spectral_gate',
    name: 'SpectralGate',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'threshold', label: 'Threshold', type: 'float', min: -80, max: 0, default: -40, unit: 'dB', step: 0.5 },
      { id: 'smoothing', label: 'Smoothing', type: 'float', min: 0, max: 1, default: 0.8, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'SpectralGatePluginUI', width: 320, height: 200 },
  },

  'spring_reverb': {
    id: 'spring_reverb',
    name: 'SpringReverb',
    version: '2.0.0',
    category: 'reverb',
    type: 'insert',
    color: '#7744ff',
    processor: { kind: 'native' },
    params: [
      { id: 'tension', label: 'Tension', type: 'float', min: 0, max: 1, default: 0.6, unit: '', step: 0.01 },
      { id: 'tanks', label: 'Tanks', type: 'float', min: 1, max: 3, default: 3, unit: '', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 30, unit: '%', step: 1 },
      { id: 'drip', label: 'Drip', type: 'float', min: 0, max: 1, default: 0.3, unit: '', step: 0.01 },
    ],
    ui: { component: 'SpringReverbPluginUI', width: 320, height: 200 },
  },

  'step_filter': {
    id: 'step_filter',
    name: 'StepFilter',
    version: '2.0.0',
    category: 'filter',
    type: 'insert',
    color: '#ffaa00',
    processor: { kind: 'native' },
    params: [
      { id: 'steps', label: 'Steps', type: 'float', min: 4, max: 16, default: 8, unit: '', step: 1 },
      { id: 'rate', label: 'Rate', type: 'float', min: 0.1, max: 10, default: 2, unit: 'Hz', step: 0.1 },
      { id: 'depth', label: 'Depth', type: 'float', min: 0, max: 1, default: 0.8, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'StepFilterPluginUI', width: 320, height: 200 },
  },

  'stereo_enhancer': {
    id: 'stereo_enhancer',
    name: 'StereoEnhancer',
    version: '2.0.0',
    category: 'spatial',
    type: 'insert',
    color: '#44ffaa',
    processor: { kind: 'native' },
    params: [
      { id: 'width', label: 'Width', type: 'float', min: 0, max: 200, default: 100, unit: '%', step: 1 },
      { id: 'bass', label: 'Bass', type: 'float', min: 0, max: 1, default: 0, unit: '', step: 0.01 },
      { id: 'mono', label: 'Mono', type: 'float', min: 0, max: 1, default: 0, unit: '', step: 1 },
    ],
    ui: { component: 'StereoEnhancerPluginUI', width: 320, height: 200 },
  },

  'stereo_widener': {
    id: 'stereo_widener',
    name: 'StereoWidener',
    version: '2.0.0',
    category: 'spatial',
    type: 'insert',
    color: '#44ffaa',
    processor: { kind: 'native' },
    params: [
      { id: 'width', label: 'Width', type: 'float', min: 0, max: 200, default: 100, unit: '%', step: 1 },
      { id: 'monoBelow', label: 'Monobelow', type: 'float', min: 20, max: 300, default: 100, unit: 'Hz', step: 5 },
    ],
    ui: { component: 'StereoWidenerPluginUI', width: 320, height: 200 },
  },

  'sub_harmonizer': {
    id: 'sub_harmonizer',
    name: 'SubHarmonizer',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'octave', label: 'Octave', type: 'float', min: -2, max: -1, default: -1, unit: 'oct', step: 1 },
      { id: 'level', label: 'Level', type: 'float', min: 0, max: 12, default: 4, unit: 'dB', step: 0.1 },
      { id: 'filter', label: 'Filter', type: 'float', min: 40, max: 200, default: 80, unit: 'Hz', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
    ],
    ui: { component: 'SubHarmonizerPluginUI', width: 320, height: 200 },
  },

  'tape_delay': {
    id: 'tape_delay',
    name: 'TapeDelay',
    version: '2.0.0',
    category: 'delay',
    type: 'insert',
    color: '#00aaff',
    processor: { kind: 'native' },
    params: [
      { id: 'time', label: 'Time', type: 'float', min: 10, max: 2000, default: 500, unit: 'ms', step: 1 },
      { id: 'feedback', label: 'Feedback', type: 'float', min: 0, max: 0.95, default: 0.4, unit: '', step: 0.01 },
      { id: 'wow', label: 'Wow', type: 'float', min: 0, max: 0.02, default: 0.003, unit: '', step: 0.001 },
      { id: 'tone', label: 'Tone', type: 'float', min: 200, max: 8000, default: 4000, unit: 'Hz', step: 100 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 30, unit: '%', step: 1 },
    ],
    ui: { component: 'TapeDelayPluginUI', width: 320, height: 200 },
  },

  'tape_warmth': {
    id: 'tape_warmth',
    name: 'TapeWarmth',
    version: '2.0.0',
    category: 'distortion',
    type: 'insert',
    color: '#ff6600',
    processor: { kind: 'native' },
    params: [
      { id: 'drive', label: 'Drive', type: 'float', min: 0, max: 1, default: 0.4, unit: '', step: 0.01 },
      { id: 'hfLoss', label: 'Hfloss', type: 'float', min: 0, max: 1, default: 0.3, unit: '', step: 0.01 },
      { id: 'noise', label: 'Noise', type: 'float', min: 0, max: 0.1, default: 0.01, unit: '', step: 0.001 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'TapeWarmthPluginUI', width: 320, height: 200 },
  },

  'tilt_e_q': {
    id: 'tilt_e_q',
    name: 'TiltEQ',
    version: '2.0.0',
    category: 'eq',
    type: 'insert',
    color: '#5ac8fa',
    processor: { kind: 'native' },
    params: [
      { id: 'tilt', label: 'Tilt', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.1 },
      { id: 'pivot', label: 'Pivot', type: 'float', min: 200, max: 8000, default: 1000, unit: 'Hz', step: 50 },
      { id: 'air', label: 'Air', type: 'float', min: -6, max: 12, default: 0, unit: 'dB', step: 0.1 },
    ],
    ui: { component: 'TiltEQPluginUI', width: 320, height: 200 },
  },

  'transient_designer': {
    id: 'transient_designer',
    name: 'TransientDesigner',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'attack', label: 'Attack', type: 'float', min: -24, max: 24, default: 0, unit: 'dB', step: 0.5 },
      { id: 'sustain', label: 'Sustain', type: 'float', min: -24, max: 24, default: 0, unit: 'dB', step: 0.5 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'TransientDesignerPluginUI', width: 320, height: 200 },
  },

  'tremolo': {
    id: 'tremolo',
    name: 'Tremolo',
    version: '2.0.0',
    category: 'modulation',
    type: 'insert',
    color: '#ff44aa',
    processor: { kind: 'native' },
    params: [
      { id: 'rate', label: 'Rate', type: 'float', min: 0.1, max: 20, default: 4, unit: 'Hz', step: 0.1 },
      { id: 'depth', label: 'Depth', type: 'float', min: 0, max: 1, default: 0.7, unit: '', step: 0.01 },
      { id: 'wave', label: 'Wave', type: 'float', min: 0, max: 3, default: 0, unit: '', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'TremoloPluginUI', width: 320, height: 200 },
  },

  'tube_comp': {
    id: 'tube_comp',
    name: 'TubeComp',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'threshold', label: 'Threshold', type: 'float', min: -40, max: 0, default: -18, unit: 'dB', step: 0.5 },
      { id: 'ratio', label: 'Ratio', type: 'float', min: 1, max: 20, default: 4, unit: ':1', step: 0.1 },
      { id: 'attack', label: 'Attack', type: 'float', min: 0.1, max: 200, default: 10, unit: 'ms', step: 0.1 },
      { id: 'release', label: 'Release', type: 'float', min: 10, max: 2000, default: 150, unit: 'ms', step: 5 },
      { id: 'tubeSat', label: 'Tubesat', type: 'float', min: 0, max: 1, default: 0.4, unit: '', step: 0.01 },
    ],
    ui: { component: 'TubeCompPluginUI', width: 320, height: 200 },
  },

  'tube_saturator': {
    id: 'tube_saturator',
    name: 'TubeSaturator',
    version: '2.0.0',
    category: 'distortion',
    type: 'insert',
    color: '#ff6600',
    processor: { kind: 'native' },
    params: [
      { id: 'drive', label: 'Drive', type: 'float', min: 0, max: 1, default: 0.4, unit: '', step: 0.01 },
      { id: 'even', label: 'Even', type: 'float', min: 0, max: 1, default: 0.7, unit: '', step: 0.01 },
      { id: 'odd', label: 'Odd', type: 'float', min: 0, max: 1, default: 0.3, unit: '', step: 0.01 },
      { id: 'bias', label: 'Bias', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'TubeSaturatorPluginUI', width: 320, height: 200 },
  },

  'v_c_a_comp': {
    id: 'v_c_a_comp',
    name: 'VCAComp',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'threshold', label: 'Threshold', type: 'float', min: -40, max: 0, default: -10, unit: 'dB', step: 0.5 },
      { id: 'ratio', label: 'Ratio', type: 'float', min: 1.5, max: 10, default: 4, unit: ':1', step: 0.1 },
      { id: 'attack', label: 'Attack', type: 'float', min: 0.1, max: 30, default: 3, unit: 'ms', step: 0.1 },
      { id: 'release', label: 'Release', type: 'float', min: 50, max: 1200, default: 100, unit: 'ms', step: 5 },
      { id: 'makeup', label: 'Makeup', type: 'float', min: 0, max: 12, default: 2, unit: 'dB', step: 0.5 },
    ],
    ui: { component: 'VCACompPluginUI', width: 320, height: 200 },
  },

  'vibrato': {
    id: 'vibrato',
    name: 'Vibrato',
    version: '2.0.0',
    category: 'modulation',
    type: 'insert',
    color: '#ff44aa',
    processor: { kind: 'native' },
    params: [
      { id: 'rate', label: 'Rate', type: 'float', min: 0.1, max: 10, default: 3, unit: 'Hz', step: 0.1 },
      { id: 'depth', label: 'Depth', type: 'float', min: 0, max: 0.02, default: 0.005, unit: '', step: 0.0001 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'VibratoPluginUI', width: 320, height: 200 },
  },

  'vinyl_sim': {
    id: 'vinyl_sim',
    name: 'VinylSim',
    version: '2.0.0',
    category: 'distortion',
    type: 'insert',
    color: '#ff6600',
    processor: { kind: 'native' },
    params: [
      { id: 'warmth', label: 'Warmth', type: 'float', min: 0, max: 1, default: 0.6, unit: '', step: 0.01 },
      { id: 'crackle', label: 'Crackle', type: 'float', min: 0, max: 1, default: 0.2, unit: '', step: 0.01 },
      { id: 'dust', label: 'Dust', type: 'float', min: 0, max: 1, default: 0.15, unit: '', step: 0.01 },
      { id: 'warp', label: 'Warp', type: 'float', min: 0, max: 1, default: 0.1, unit: '', step: 0.01 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'VinylSimPluginUI', width: 320, height: 200 },
  },

  'vocal_comp': {
    id: 'vocal_comp',
    name: 'VocalComp',
    version: '2.0.0',
    category: 'dynamics',
    type: 'insert',
    color: '#ff6b6b',
    processor: { kind: 'native' },
    params: [
      { id: 'threshold', label: 'Threshold', type: 'float', min: -40, max: 0, default: -18, unit: 'dB', step: 0.5 },
      { id: 'ratio', label: 'Ratio', type: 'float', min: 1, max: 10, default: 3, unit: ':1', step: 0.1 },
      { id: 'attack', label: 'Attack', type: 'float', min: 0.1, max: 50, default: 5, unit: 'ms', step: 0.1 },
      { id: 'release', label: 'Release', type: 'float', min: 10, max: 500, default: 80, unit: 'ms', step: 5 },
      { id: 'makeup', label: 'Makeup', type: 'float', min: 0, max: 24, default: 0, unit: 'dB', step: 0.5 },
    ],
    ui: { component: 'VocalCompPluginUI', width: 320, height: 200 },
  },

  'vocal_doubler': {
    id: 'vocal_doubler',
    name: 'VocalDoubler',
    version: '2.0.0',
    category: 'vocal',
    type: 'insert',
    color: '#ff99cc',
    processor: { kind: 'native' },
    params: [
      { id: 'delay', label: 'Delay', type: 'float', min: 5, max: 50, default: 18, unit: 'ms', step: 0.5 },
      { id: 'spread', label: 'Spread', type: 'float', min: 0, max: 1, default: 0.8, unit: '', step: 0.01 },
      { id: 'detune', label: 'Detune', type: 'float', min: -20, max: 20, default: 0, unit: '¢', step: 0.5 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
    ],
    ui: { component: 'VocalDoublerPluginUI', width: 320, height: 200 },
  },

  'vocal_enhancer': {
    id: 'vocal_enhancer',
    name: 'VocalEnhancer',
    version: '2.0.0',
    category: 'vocal',
    type: 'insert',
    color: '#ff99cc',
    processor: { kind: 'native' },
    params: [
      { id: 'presence', label: 'Presence', type: 'float', min: 0, max: 12, default: 3, unit: 'dB', step: 0.1 },
      { id: 'air', label: 'Air', type: 'float', min: 0, max: 9, default: 2, unit: 'dB', step: 0.1 },
      { id: 'warmth', label: 'Warmth', type: 'float', min: 0, max: 6, default: 1, unit: 'dB', step: 0.1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'VocalEnhancerPluginUI', width: 320, height: 200 },
  },

  'vowel_filter': {
    id: 'vowel_filter',
    name: 'VowelFilter',
    version: '2.0.0',
    category: 'filter',
    type: 'insert',
    color: '#ffaa00',
    processor: { kind: 'native' },
    params: [
      { id: 'vowel', label: 'Vowel', type: 'float', min: 0, max: 4, default: 0, unit: '', step: 1 },
      { id: 'morph', label: 'Morph', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'q', label: 'Q', type: 'float', min: 1, max: 20, default: 8, unit: '', step: 0.1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'VowelFilterPluginUI', width: 320, height: 200 },
  },

  'wah_wah': {
    id: 'wah_wah',
    name: 'WahWah',
    version: '2.0.0',
    category: 'filter',
    type: 'insert',
    color: '#ffaa00',
    processor: { kind: 'native' },
    params: [
      { id: 'freq', label: 'Freq', type: 'float', min: 200, max: 4000, default: 800, unit: 'Hz', step: 10 },
      { id: 'q', label: 'Q', type: 'float', min: 1, max: 20, default: 5, unit: '', step: 0.1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
      { id: 'auto', label: 'Auto', type: 'float', min: 0, max: 1, default: 0, unit: '', step: 1 },
      { id: 'rate', label: 'Rate', type: 'float', min: 0.1, max: 10, default: 2, unit: 'Hz', step: 0.1 },
    ],
    ui: { component: 'WahWahPluginUI', width: 320, height: 200 },
  },

  'waveshaper': {
    id: 'waveshaper',
    name: 'Waveshaper',
    version: '2.0.0',
    category: 'distortion',
    type: 'insert',
    color: '#ff6600',
    processor: { kind: 'native' },
    params: [
      { id: 'drive', label: 'Drive', type: 'float', min: 0, max: 1, default: 0.5, unit: '', step: 0.01 },
      { id: 'curve', label: 'Curve', type: 'float', min: 0, max: 4, default: 0, unit: '', step: 1 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 50, unit: '%', step: 1 },
      { id: 'outputGain', label: 'Outputgain', type: 'float', min: -12, max: 12, default: 0, unit: 'dB', step: 0.5 },
    ],
    ui: { component: 'WaveshaperPluginUI', width: 320, height: 200 },
  },

  'wow_flutter': {
    id: 'wow_flutter',
    name: 'WowFlutter',
    version: '2.0.0',
    category: 'modulation',
    type: 'insert',
    color: '#ff44aa',
    processor: { kind: 'native' },
    params: [
      { id: 'wow', label: 'Wow', type: 'float', min: 0, max: 0.1, default: 0.02, unit: '', step: 0.001 },
      { id: 'flutter', label: 'Flutter', type: 'float', min: 0, max: 0.05, default: 0.01, unit: '', step: 0.001 },
      { id: 'speed', label: 'Speed', type: 'float', min: 3.75, max: 30, default: 15, unit: 'ips', step: 0.25 },
      { id: 'mix', label: 'Mix', type: 'float', min: 0, max: 100, default: 100, unit: '%', step: 1 },
    ],
    ui: { component: 'WowFlutterPluginUI', width: 320, height: 200 },
  },
};

export default pluginRegistry;
export const getPlugin = (id) => pluginRegistry[id] || null;
export const getAllPlugins = () => Object.values(pluginRegistry);
export const getPluginsByCategory = (cat) => getAllPlugins().filter(p => p.category === cat);
export const CATEGORIES = ['dynamics','eq','reverb','delay','modulation','filter','distortion','pitch','vocal','spatial','utility','mastering','restoration','creative'];
export const getCategories = () => [...new Set(getAllPlugins().map(p => p.category))].sort();
export const getPluginDef = (id) => pluginRegistry[id] || null;
