"""empty message

Revision ID: 05c3c8396e67
Revises: ffb1d56b6701
Create Date: 2025-03-26 04:08:13.462470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c3c8396e67'
down_revision = 'ffb1d56b6701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast_episode_interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['podcast_episode.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_cut', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('creator_earnings', sa.Float(), nullable=True))

    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_cut', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('creator_earnings', sa.Float(), nullable=True))

    with op.batch_alter_table('podcast_episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_revenue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('revenue_from_ads', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('revenue_from_subscriptions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('platform_cut', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('creator_earnings', sa.Float(), nullable=True))

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_cut', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('creator_earnings', sa.Float(), nullable=True))

    with op.batch_alter_table('subscription_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_cut', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('creator_earnings', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plan', schema=None) as batch_op:
        batch_op.drop_column('creator_earnings')
        batch_op.drop_column('platform_cut')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('creator_earnings')
        batch_op.drop_column('platform_cut')

    with op.batch_alter_table('podcast_episode', schema=None) as batch_op:
        batch_op.drop_column('creator_earnings')
        batch_op.drop_column('platform_cut')
        batch_op.drop_column('revenue_from_subscriptions')
        batch_op.drop_column('revenue_from_ads')
        batch_op.drop_column('total_revenue')

    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.drop_column('creator_earnings')
        batch_op.drop_column('platform_cut')

    with op.batch_alter_table('live_event', schema=None) as batch_op:
        batch_op.drop_column('creator_earnings')
        batch_op.drop_column('platform_cut')

    op.drop_table('podcast_episode_interaction')
    # ### end Alembic commands ###
