"""add audio_type bpm_detected key_detected to audio

Revision ID: 0aaa3d8afaee
Revises: f67e90e43d51
Create Date: 2026-03-13 18:39:44.530521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aaa3d8afaee'
down_revision = 'f67e90e43d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bpm_detected', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('key_detected', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio', schema=None) as batch_op:
        batch_op.drop_column('key_detected')
        batch_op.drop_column('bpm_detected')
        batch_op.drop_column('audio_type')

    # ### end Alembic commands ###
