"""empty message

Revision ID: 0caa2c5f8781
Revises: 66949ed11493
Create Date: 2026-02-20 00:56:28.329271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0caa2c5f8781'
down_revision = '66949ed11493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('includes_ai_mastering', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_mastering_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('includes_ai_radio_dj', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('includes_ai_voice_clone', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ai_dj_personas', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_plans', schema=None) as batch_op:
        batch_op.drop_column('ai_dj_personas')
        batch_op.drop_column('includes_ai_voice_clone')
        batch_op.drop_column('includes_ai_radio_dj')
        batch_op.drop_column('ai_mastering_limit')
        batch_op.drop_column('includes_ai_mastering')

    # ### end Alembic commands ###
