"""empty message

Revision ID: 1926217b83bd
Revises: 3a5e8aabf0ed
Create Date: 2025-05-28 23:20:03.266401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1926217b83bd'
down_revision = '3a5e8aabf0ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###
