"""add spx canvas models

Revision ID: 2b89000c71e8
Revises: 7fba29941924
Create Date: 2026-03-19 02:43:22.610073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b89000c71e8'
down_revision = '7fba29941924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvas_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canvas_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canvas_asset_user_id'), ['user_id'], unique=False)

    op.create_table('canvas_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('background', sa.String(length=32), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canvas_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canvas_project_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canvas_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canvas_project_user_id'))

    op.drop_table('canvas_project')
    with op.batch_alter_table('canvas_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canvas_asset_user_id'))

    op.drop_table('canvas_asset')
    # ### end Alembic commands ###
