"""add ai_jobs table

Revision ID: 2e4b5d871aa6
Revises: fcf975a6e2e9
Create Date: 2026-03-12 03:54:58.066366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4b5d871aa6'
down_revision = 'fcf975a6e2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('output_url', sa.String(length=500), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('refunded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_jobs_feature'), ['feature'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_jobs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_ai_jobs_feature'))

    op.drop_table('ai_jobs')
    # ### end Alembic commands ###
