"""empty message

Revision ID: 2e773e3e9b99
Revises: 00a267bbd4d8
Create Date: 2026-02-22 01:46:20.597179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e773e3e9b99'
down_revision = '00a267bbd4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('sub_genre', sa.String(length=100), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=10), nullable=True),
    sa.Column('duration', sa.String(length=10), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=False),
    sa.Column('mp3_url', sa.String(length=500), nullable=True),
    sa.Column('wav_url', sa.String(length=500), nullable=True),
    sa.Column('stems_url', sa.String(length=500), nullable=True),
    sa.Column('artwork_url', sa.String(length=500), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('exclusive_price', sa.Float(), nullable=True),
    sa.Column('is_sold_exclusive', sa.Boolean(), nullable=True),
    sa.Column('plays', sa.Integer(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('total_sales', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_free_download', sa.Boolean(), nullable=True),
    sa.Column('allow_offers', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('audio_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audio.id'], ),
    sa.ForeignKeyConstraint(['producer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beat_licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beat_id', sa.Integer(), nullable=False),
    sa.Column('license_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('file_format', sa.String(length=50), nullable=False),
    sa.Column('includes_stems', sa.Boolean(), nullable=True),
    sa.Column('distribution_limit', sa.Integer(), nullable=True),
    sa.Column('streaming_limit', sa.Integer(), nullable=True),
    sa.Column('music_video', sa.Boolean(), nullable=True),
    sa.Column('radio_broadcasting', sa.Boolean(), nullable=True),
    sa.Column('live_performance', sa.Boolean(), nullable=True),
    sa.Column('is_exclusive', sa.Boolean(), nullable=True),
    sa.Column('credit_required', sa.Boolean(), nullable=True),
    sa.Column('custom_terms', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beat_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beat_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('platform_cut', sa.Float(), nullable=False),
    sa.Column('producer_earnings', sa.Float(), nullable=False),
    sa.Column('stripe_payment_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('license_type', sa.String(length=50), nullable=False),
    sa.Column('license_name', sa.String(length=100), nullable=False),
    sa.Column('file_format', sa.String(length=50), nullable=False),
    sa.Column('distribution_limit', sa.Integer(), nullable=True),
    sa.Column('streaming_limit', sa.Integer(), nullable=True),
    sa.Column('includes_stems', sa.Boolean(), nullable=True),
    sa.Column('is_exclusive', sa.Boolean(), nullable=True),
    sa.Column('contract_url', sa.String(length=500), nullable=True),
    sa.Column('contract_signed_at', sa.DateTime(), nullable=True),
    sa.Column('buyer_legal_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_artist_name', sa.String(length=255), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('last_downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['license_id'], ['beat_licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beat_purchases')
    op.drop_table('beat_licenses')
    op.drop_table('beats')
    # ### end Alembic commands ###
