"""add video_series table

Revision ID: 2f55cf000a0f
Revises: 6edf216c225c
Create Date: 2026-03-07 02:54:34.488403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f55cf000a0f'
down_revision = '6edf216c225c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('episodes_json', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collab_application', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('collab_application_request_id_user_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('collab_application_request_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'collab_request', ['request_id'], ['id'])

    with op.batch_alter_table('creator_payment_settings', schema=None) as batch_op:
        batch_op.alter_column('tip_message',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('cashapp_username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('venmo_username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('zelle_enabled')
        batch_op.drop_column('zelle_identifier')
        batch_op.drop_column('tip_minimum')
        batch_op.drop_column('accepts_platform_tips')
        batch_op.drop_column('paypal_username')

    with op.batch_alter_table('credit_pack_purchases', schema=None) as batch_op:
        batch_op.alter_column('pack_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('pack_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('stripe_checkout_session_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('stripe_payment_intent_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('credit_pack_purchases_stripe_checkout_session_id_key'), type_='unique')

    with op.batch_alter_table('epk', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('epk_slug_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_epk_user'))
        batch_op.drop_index(batch_op.f('ix_epk_slug'))
        batch_op.create_index(batch_op.f('ix_epk_slug'), ['slug'], unique=True)

    with op.batch_alter_table('mastering_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('was_auto_detected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    op.execute("UPDATE recording_projects SET tags = '[]' WHERE tags IS NULL")
    op.execute("UPDATE recording_projects SET status = 'draft' WHERE status IS NULL")
    op.execute("UPDATE recording_projects SET bpm = 120 WHERE bpm IS NULL")
    op.execute("UPDATE recording_projects SET tracks_json = '[]' WHERE tracks_json IS NULL")
    op.execute("UPDATE recording_projects SET track_audio_urls = '{}' WHERE track_audio_urls IS NULL")
    op.execute("UPDATE recording_projects SET piano_roll_notes_json = '[]' WHERE piano_roll_notes_json IS NULL")
    op.execute("UPDATE recording_projects SET piano_roll_key = 'C' WHERE piano_roll_key IS NULL")
    op.execute("UPDATE recording_projects SET piano_roll_scale = 'major' WHERE piano_roll_scale IS NULL")
    op.execute("UPDATE recording_projects SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE recording_projects SET updated_at = NOW() WHERE updated_at IS NULL")
    with op.batch_alter_table('recording_projects', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('tags',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('bpm',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('time_signature_top',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('time_signature_bottom',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('master_volume',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('metronome_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('count_in_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('duration_seconds',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('sample_rate',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tracks_json',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('track_audio_urls',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('piano_roll_notes_json',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('piano_roll_key',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('piano_roll_scale',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('mixdown_bit_depth',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('mixdown_channels',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('total_size_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('track_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording_projects', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('track_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_size_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('mixdown_channels',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mixdown_bit_depth',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('piano_roll_scale',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('piano_roll_key',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('piano_roll_notes_json',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('track_audio_urls',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('tracks_json',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('sample_rate',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('duration_seconds',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('count_in_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('metronome_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('master_volume',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('time_signature_bottom',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('time_signature_top',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bpm',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tags',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('mastering_jobs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('was_auto_detected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('epk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_epk_slug'))
        batch_op.create_index(batch_op.f('ix_epk_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_epk_user'), ['user_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('epk_slug_key'), ['slug'])

    with op.batch_alter_table('credit_pack_purchases', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('credit_pack_purchases_stripe_checkout_session_id_key'), ['stripe_checkout_session_id'])
        batch_op.alter_column('stripe_payment_intent_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('stripe_checkout_session_id',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('pack_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('pack_id',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('creator_payment_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('accepts_platform_tips', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tip_minimum', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('zelle_identifier', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('zelle_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('venmo_username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('cashapp_username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('tip_message',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('collab_application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('collab_application_request_id_fkey'), 'collab_request', ['request_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('collab_application_request_id_user_id_key'), ['request_id', 'user_id'])

    op.drop_table('video_series')
    # ### end Alembic commands ###
