"""empty message

Revision ID: 307590f4a720
Revises: 26c860bf2d4a
Create Date: 2025-03-25 23:15:23.366881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307590f4a720'
down_revision = '26c860bf2d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vr_access_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['live_event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vr_access_ticket')
    # ### end Alembic commands ###
