"""empty message

Revision ID: 3db7d8d1c2dc
Revises: 8696b7628765
Create Date: 2026-01-13 23:49:52.716383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db7d8d1c2dc'
down_revision = '8696b7628765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='unique_block')
    )
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.create_index('idx_blocked', ['blocked_id'], unique=False)
        batch_op.create_index('idx_blocker', ['blocker_id'], unique=False)

    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='unique_follow')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('idx_follower', ['follower_id'], unique=False)
        batch_op.create_index('idx_following', ['following_id'], unique=False)

    op.drop_table('follow')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('following_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')
        batch_op.drop_column('is_active')
        batch_op.drop_column('following_count')
        batch_op.drop_column('follower_count')

    op.create_table('follow',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name=op.f('follow_followed_id_fkey')),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name=op.f('follow_follower_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('follow_pkey'))
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index('idx_following')
        batch_op.drop_index('idx_follower')

    op.drop_table('follows')
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_index('idx_blocker')
        batch_op.drop_index('idx_blocked')

    op.drop_table('blocks')
    # ### end Alembic commands ###
