"""empty message

Revision ID: 4298d93fad1a
Revises: 97a83fa2261e
Create Date: 2025-08-06 10:29:08.733792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4298d93fad1a'
down_revision = '97a83fa2261e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('release_title', sa.String(length=200), nullable=False),
    sa.Column('artist_name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('release_type', sa.String(length=20), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('distribution_service', sa.String(length=50), nullable=True),
    sa.Column('sonosuite_release_id', sa.String(length=100), nullable=True),
    sa.Column('external_release_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('expected_live_date', sa.DateTime(), nullable=True),
    sa.Column('live_date', sa.DateTime(), nullable=True),
    sa.Column('takedown_date', sa.DateTime(), nullable=True),
    sa.Column('platforms', sa.Text(), nullable=True),
    sa.Column('territories', sa.Text(), nullable=True),
    sa.Column('total_streams', sa.BigInteger(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_revenue_update', sa.DateTime(), nullable=True),
    sa.Column('isrc_code', sa.String(length=20), nullable=True),
    sa.Column('upc_code', sa.String(length=20), nullable=True),
    sa.Column('explicit_content', sa.Boolean(), nullable=True),
    sa.Column('copyright_info', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sonosuite_response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['audio.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribution_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distribution_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('territory', sa.String(length=10), nullable=True),
    sa.Column('streams', sa.BigInteger(), nullable=True),
    sa.Column('downloads', sa.BigInteger(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_period', sa.String(length=20), nullable=True),
    sa.Column('unique_listeners', sa.Integer(), nullable=True),
    sa.Column('playlist_adds', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['distribution_id'], ['music_distributions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distribution_analytics')
    op.drop_table('music_distributions')
    # ### end Alembic commands ###
