"""empty message

Revision ID: 446781aeca4f
Revises: fdcb47b19f2a
Create Date: 2025-11-08 15:43:51.709497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446781aeca4f'
down_revision = 'fdcb47b19f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('plays_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('likes_count')
        batch_op.drop_column('plays_count')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
