"""empty message

Revision ID: 45299e8be404
Revises: 71e5f784050c
Create Date: 2025-08-29 16:32:58.555469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45299e8be404'
down_revision = '71e5f784050c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_clip_max_size', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('audio_clip_max_size', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('image_max_size', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('project_total_max_size', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('max_clips_per_track', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_tracks_per_project', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_projects', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('export_formats', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('max_export_quality', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('max_export_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('platform_export_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allowed_platforms', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('audio_separation_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('advanced_effects_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('collaboration_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('priority_export_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_plan', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('priority_export_enabled')
        batch_op.drop_column('collaboration_enabled')
        batch_op.drop_column('advanced_effects_enabled')
        batch_op.drop_column('audio_separation_enabled')
        batch_op.drop_column('allowed_platforms')
        batch_op.drop_column('platform_export_enabled')
        batch_op.drop_column('max_export_duration')
        batch_op.drop_column('max_export_quality')
        batch_op.drop_column('export_formats')
        batch_op.drop_column('max_projects')
        batch_op.drop_column('max_tracks_per_project')
        batch_op.drop_column('max_clips_per_track')
        batch_op.drop_column('project_total_max_size')
        batch_op.drop_column('image_max_size')
        batch_op.drop_column('audio_clip_max_size')
        batch_op.drop_column('video_clip_max_size')

    # ### end Alembic commands ###
