"""add final tier ai controls previews

Revision ID: 49d0ff06420f
Revises: 9da939427a69
Create Date: 2026-03-19 22:50:27.996788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d0ff06420f'
down_revision = '9da939427a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_task_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('control_state', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('progress_pct', sa.Integer(), nullable=True))

    with op.batch_alter_table('lesson_timelines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_urls', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preview_sprite_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_timelines', schema=None) as batch_op:
        batch_op.drop_column('preview_sprite_url')
        batch_op.drop_column('thumbnail_urls')

    with op.batch_alter_table('ai_task_jobs', schema=None) as batch_op:
        batch_op.drop_column('progress_pct')
        batch_op.drop_column('control_state')

    # ### end Alembic commands ###
