"""empty message

Revision ID: 49fa15606498
Revises: 18b050aa4fda
Create Date: 2026-02-10 02:29:31.152903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49fa15606498'
down_revision = '18b050aa4fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('story_replies')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_content_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shared_content_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('shared_from_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('allow_reshare', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_comments', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('views_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comments_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shares_count', sa.Integer(), nullable=True))
        batch_op.alter_column('media_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('media_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('caption',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('highlight_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('stories_music_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['shared_from_user_id'], ['id'])
        batch_op.drop_column('comment_mode')
        batch_op.drop_column('music_id')
        batch_op.drop_column('view_count')

    with op.batch_alter_table('story_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reaction', sa.String(length=10), nullable=True))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('story_comments_parent_id_fkey'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('story_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('unique_story_view'), type_='unique')
        batch_op.create_unique_constraint('unique_story_view', ['story_id', 'user_id'])
        batch_op.drop_constraint(batch_op.f('story_views_viewer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('viewer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewer_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('story_views_viewer_id_fkey'), 'user', ['viewer_id'], ['id'])
        batch_op.drop_constraint('unique_story_view', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_story_view'), ['story_id', 'viewer_id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('story_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('story_comments_parent_id_fkey'), 'story_comments', ['parent_id'], ['id'])
        batch_op.alter_column('text',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.drop_column('reaction')

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('music_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comment_mode', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('stories_music_id_fkey'), 'audio', ['music_id'], ['id'])
        batch_op.alter_column('highlight_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('caption',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('media_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('media_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('shares_count')
        batch_op.drop_column('comments_count')
        batch_op.drop_column('likes_count')
        batch_op.drop_column('views_count')
        batch_op.drop_column('allow_comments')
        batch_op.drop_column('allow_reshare')
        batch_op.drop_column('shared_from_user_id')
        batch_op.drop_column('shared_content_type')
        batch_op.drop_column('shared_content_id')

    op.create_table('story_replies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('story_replies_sender_id_fkey')),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('story_replies_story_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('story_replies_pkey'))
    )
    op.drop_table('story_highlights')
    # ### end Alembic commands ###
