"""empty message

Revision ID: 55a755d1c658
Revises: add_gamer_profile_fields
Create Date: 2025-07-12 14:37:39.363341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a755d1c658'
down_revision = 'add_gamer_profile_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radio_station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('submission_guidelines', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('creator_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('preferred_genres', sa.ARRAY(sa.String()), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_artist', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('artist_bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('artist_genre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('artist_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('artist_website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('artist_social_links', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_verified_artist', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('monthly_listeners', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_plays', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_plays')
        batch_op.drop_column('monthly_listeners')
        batch_op.drop_column('is_verified_artist')
        batch_op.drop_column('artist_social_links')
        batch_op.drop_column('artist_website')
        batch_op.drop_column('artist_location')
        batch_op.drop_column('artist_genre')
        batch_op.drop_column('artist_bio')
        batch_op.drop_column('is_artist')

    with op.batch_alter_table('radio_station', schema=None) as batch_op:
        batch_op.drop_column('preferred_genres')
        batch_op.drop_column('creator_name')
        batch_op.drop_column('submission_guidelines')
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
