"""empty message

Revision ID: 593a08b454dc
Revises: 0caa2c5f8781
Create Date: 2026-02-20 18:15:08.912497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593a08b454dc'
down_revision = '0caa2c5f8781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recording_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('time_signature_top', sa.Integer(), nullable=True),
    sa.Column('time_signature_bottom', sa.Integer(), nullable=True),
    sa.Column('master_volume', sa.Float(), nullable=True),
    sa.Column('metronome_enabled', sa.Boolean(), nullable=True),
    sa.Column('count_in_enabled', sa.Boolean(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('tracks_json', sa.Text(), nullable=True),
    sa.Column('track_audio_urls', sa.Text(), nullable=True),
    sa.Column('mixdown_url', sa.String(length=500), nullable=True),
    sa.Column('mixdown_format', sa.String(length=10), nullable=True),
    sa.Column('mixdown_bit_depth', sa.Integer(), nullable=True),
    sa.Column('mixdown_channels', sa.Integer(), nullable=True),
    sa.Column('mixdown_created_at', sa.DateTime(), nullable=True),
    sa.Column('cover_art_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('distribution_id', sa.Integer(), nullable=True),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['distribution_id'], ['music_distribution.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recording_projects')
    # ### end Alembic commands ###
