"""empty message

Revision ID: 66949ed11493
Revises: 948ee83581d6
Create Date: 2026-02-11 01:29:33.655484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66949ed11493'
down_revision = '948ee83581d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('file_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dj_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('recorded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('play_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.alter_column('station_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('station_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('is_public')
        batch_op.drop_column('play_count')
        batch_op.drop_column('created_at')
        batch_op.drop_column('recorded_at')
        batch_op.drop_column('genre')
        batch_op.drop_column('dj_name')
        batch_op.drop_column('duration')
        batch_op.drop_column('cover_image_url')
        batch_op.drop_column('file_url')
        batch_op.drop_column('description')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
