"""empty message

Revision ID: 6e79b11b597b
Revises: c5276dcf567a
Create Date: 2026-02-21 11:55:22.283599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e79b11b597b'
down_revision = 'c5276dcf567a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mic_sim_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_profile', sa.String(length=50), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('noise_gate_enabled', sa.Boolean(), nullable=True),
    sa.Column('noise_gate_threshold', sa.Float(), nullable=True),
    sa.Column('input_gain', sa.Float(), nullable=True),
    sa.Column('output_gain', sa.Float(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mic_sim_recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('mic_profile', sa.String(length=50), nullable=True),
    sa.Column('preset_id', sa.Integer(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=300), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['preset_id'], ['mic_sim_presets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mic_sim_recordings')
    op.drop_table('mic_sim_presets')
    # ### end Alembic commands ###
