"""add merch models

Revision ID: 6fd3ffe3ec61
Revises: 2e4b5d871aa6
Create Date: 2026-03-12 04:33:18.833786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd3ffe3ec61'
down_revision = '2e4b5d871aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('printful_product_id', sa.Integer(), nullable=False),
    sa.Column('printful_variant_id', sa.Integer(), nullable=False),
    sa.Column('retail_price', sa.Float(), nullable=False),
    sa.Column('artwork_url', sa.String(length=500), nullable=True),
    sa.Column('mockup_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merch_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('retail_price', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=True),
    sa.Column('stripe_payment_intent', sa.String(length=200), nullable=True),
    sa.Column('printful_order_id', sa.String(length=100), nullable=True),
    sa.Column('shipping_name', sa.String(length=200), nullable=True),
    sa.Column('shipping_address', sa.String(length=300), nullable=True),
    sa.Column('shipping_city', sa.String(length=100), nullable=True),
    sa.Column('shipping_state', sa.String(length=50), nullable=True),
    sa.Column('shipping_country', sa.String(length=10), nullable=True),
    sa.Column('shipping_zip', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['creator_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merch_orders')
    op.drop_table('creator_products')
    # ### end Alembic commands ###
