"""Add video channel customization fields

Revision ID: 71e5f784050c
Revises: c2c95d07c4ef
Create Date: 2025-08-19 17:57:55.092124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e5f784050c'
down_revision = 'c2c95d07c4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_url', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('watermark_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('primary_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('secondary_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('allow_comments', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_likes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('age_restricted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('made_for_kids', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('enable_monetization', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('theme_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('accent_color', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('custom_css', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tiktok_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('discord_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitch_url', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['custom_url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_channels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('twitch_url')
        batch_op.drop_column('discord_url')
        batch_op.drop_column('tiktok_url')
        batch_op.drop_column('facebook_url')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('website_url')
        batch_op.drop_column('custom_css')
        batch_op.drop_column('accent_color')
        batch_op.drop_column('theme_color')
        batch_op.drop_column('enable_monetization')
        batch_op.drop_column('made_for_kids')
        batch_op.drop_column('age_restricted')
        batch_op.drop_column('allow_likes')
        batch_op.drop_column('allow_comments')
        batch_op.drop_column('language')
        batch_op.drop_column('country')
        batch_op.drop_column('secondary_category')
        batch_op.drop_column('primary_category')
        batch_op.drop_column('watermark_url')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('custom_url')

    # ### end Alembic commands ###
