"""empty message

Revision ID: 7a4ad778d114
Revises: d6075bd35182
Create Date: 2025-07-24 03:23:30.578884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a4ad778d114'
down_revision = 'd6075bd35182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')

    op.create_table('chat_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('room', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name=op.f('chat_message_recipient_id_fkey')),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('chat_message_sender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_message_pkey'))
    )
    # ### end Alembic commands ###
