"""add academy ai lesson fields

Revision ID: 7bb1865d3069
Revises: a54185ba21af
Create Date: 2026-03-19 22:23:03.753631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb1865d3069'
down_revision = 'a54185ba21af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_mode', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('avatar_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('script_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_audio_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ai_video_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ai_generation_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('generation_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('generation_status')
        batch_op.drop_column('ai_generation_id')
        batch_op.drop_column('ai_video_url')
        batch_op.drop_column('ai_audio_url')
        batch_op.drop_column('script_text')
        batch_op.drop_column('avatar_id')
        batch_op.drop_column('source_mode')

    # ### end Alembic commands ###
