"""empty message

Revision ID: 868b2d43110a
Revises: 6e79b11b597b
Create Date: 2026-02-21 15:08:27.047106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868b2d43110a'
down_revision = '6e79b11b597b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sound_kit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sound_kit_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kit_id'], ['sound_kit.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kit_id', name='unique_kit_like')
    )
    op.create_table('sound_kit_sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kit_id', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=300), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('pad_number', sa.Integer(), nullable=True),
    sa.Column('midi_note', sa.Integer(), nullable=True),
    sa.Column('root_note', sa.String(length=5), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('pan', sa.Float(), nullable=True),
    sa.Column('pitch', sa.Float(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('is_loop', sa.Boolean(), nullable=True),
    sa.Column('is_one_shot', sa.Boolean(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kit_id'], ['sound_kit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sound_kit_sample')
    op.drop_table('sound_kit_like')
    op.drop_table('sound_kit')
    # ### end Alembic commands ###
