"""empty message

Revision ID: 89256b8db9b3
Revises: 6b5188ffe8f4
Create Date: 2026-01-05 23:28:13.287635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89256b8db9b3'
down_revision = '6b5188ffe8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
