"""empty message

Revision ID: 8caa7f0335af
Revises: 55a755d1c658
Create Date: 2025-07-13 04:09:43.943430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8caa7f0335af'
down_revision = '55a755d1c658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radio_station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loop_audio_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_loop_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('loop_duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('now_playing_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('playlist_schedule', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('loop_started_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radio_station', schema=None) as batch_op:
        batch_op.drop_column('loop_started_at')
        batch_op.drop_column('playlist_schedule')
        batch_op.drop_column('now_playing_metadata')
        batch_op.drop_column('loop_duration_minutes')
        batch_op.drop_column('is_loop_enabled')
        batch_op.drop_column('loop_audio_url')

    # ### end Alembic commands ###
