"""add printful oauth fields to user

Revision ID: 8cc2a0f05232
Revises: d268b78c9a09
Create Date: 2026-03-11 21:23:35.974689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc2a0f05232'
down_revision = 'd268b78c9a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('printful_access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('printful_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('printful_token_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('printful_token_expires_at', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('printful_connected', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('printful_connected')
        batch_op.drop_column('printful_token_expires_at')
        batch_op.drop_column('printful_token_type')
        batch_op.drop_column('printful_refresh_token')
        batch_op.drop_column('printful_access_token')

    # ### end Alembic commands ###
