"""empty message

Revision ID: 8f9ad68be78d
Revises: 9b3ae07da27c
Create Date: 2025-03-18 21:24:50.461123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9ad68be78d'
down_revision = '9b3ae07da27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_revenue', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('sales_revenue')

    # ### end Alembic commands ###
