"""empty message

Revision ID: 91ef5439603e
Revises: 83d5c82ccf33
Create Date: 2025-10-19 20:20:24.615124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ef5439603e'
down_revision = '83d5c82ccf33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('age_restricted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('made_for_kids', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contains_paid_promotion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('original_content', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_comments', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_likes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_embedding', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_downloads', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'video_channels', ['channel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('allow_downloads')
        batch_op.drop_column('allow_embedding')
        batch_op.drop_column('allow_likes')
        batch_op.drop_column('allow_comments')
        batch_op.drop_column('original_content')
        batch_op.drop_column('contains_paid_promotion')
        batch_op.drop_column('made_for_kids')
        batch_op.drop_column('age_restricted')
        batch_op.drop_column('category')
        batch_op.drop_column('channel_id')

    # ### end Alembic commands ###
