"""empty message

Revision ID: 945a0250f25f
Revises: bbb43a30b934
Create Date: 2025-03-15 14:27:53.333664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945a0250f25f'
down_revision = 'bbb43a30b934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['radio_station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radio_playlist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['radio_playlist_id'], ['radio_playlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('radio_station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('radio_station', schema=None) as batch_op:
        batch_op.drop_column('cover_image_url')
        batch_op.drop_column('logo_url')

    op.drop_table('track')
    op.drop_table('archived_show')
    # ### end Alembic commands ###
