"""empty message

Revision ID: 94870c1099d1
Revises: e7ae5d534951
Create Date: 2026-01-25 04:56:12.065096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94870c1099d1'
down_revision = 'e7ae5d534951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creator_payment_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tips_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('min_tip_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('default_amounts', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('stripe_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stripe_account_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('paypal_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('crypto_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('crypto_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('crypto_network', sa.String(length=50), nullable=True))

    with op.batch_alter_table('tip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('content_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('content_id', sa.Integer(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('creator_earnings',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('stripe_payment_intent_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('source_id')
        batch_op.drop_column('platform_fee')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('stripe_checkout_session_id')
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stripe_checkout_session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('platform_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('stripe_payment_intent_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('message',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('creator_earnings',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('content_id')
        batch_op.drop_column('content_type')
        batch_op.drop_column('currency')

    with op.batch_alter_table('creator_payment_settings', schema=None) as batch_op:
        batch_op.drop_column('crypto_network')
        batch_op.drop_column('crypto_address')
        batch_op.drop_column('crypto_enabled')
        batch_op.drop_column('paypal_email')
        batch_op.drop_column('stripe_account_id')
        batch_op.drop_column('stripe_enabled')
        batch_op.drop_column('default_amounts')
        batch_op.drop_column('min_tip_amount')
        batch_op.drop_column('tips_enabled')

    # ### end Alembic commands ###
