"""empty message

Revision ID: 96de9bbbf615
Revises: e8f5f56cc528
Create Date: 2025-03-14 03:22:53.618399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96de9bbbf615'
down_revision = 'e8f5f56cc528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('manual_edit', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.Integer(), nullable=True))

    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_episode', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stripe_product_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('live_replay_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_live', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('stream_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('scheduled_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_release', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('exclusive_until', sa.DateTime(), nullable=True))
        batch_op.drop_column('season_number')
        batch_op.drop_column('transcription')
        batch_op.drop_column('episode_number')
        batch_op.drop_column('category')
        batch_op.drop_column('series_name')
        batch_op.drop_column('ad_insertion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_insertion', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('series_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('episode_number', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('transcription', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('season_number', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('exclusive_until')
        batch_op.drop_column('scheduled_release')
        batch_op.drop_column('scheduled_time')
        batch_op.drop_column('stream_url')
        batch_op.drop_column('is_live')
        batch_op.drop_column('live_replay_url')
        batch_op.drop_column('stripe_product_id')
        batch_op.drop_column('price_per_episode')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    op.drop_table('podcast_chapter')
    # ### end Alembic commands ###
