"""empty message

Revision ID: 97a83fa2261e
Revises: 7a4ad778d114
Create Date: 2025-07-28 23:39:50.799031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a83fa2261e'
down_revision = '7a4ad778d114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inner_circle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_user_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('custom_title', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('user_id != friend_user_id', name='no_self_inner_circle'),
    sa.ForeignKeyConstraint(['friend_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_user_id', name='unique_user_friend'),
    sa.UniqueConstraint('user_id', 'position', name='unique_user_position')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inner_circle')
    # ### end Alembic commands ###
