"""empty message

Revision ID: 9a3235b85b1c
Revises: 211ed80d1f86
Create Date: 2026-02-26 00:02:20.594539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a3235b85b1c'
down_revision = '211ed80d1f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('async_recording_links',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('show_name', sa.String(length=200), nullable=True),
    sa.Column('max_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studio_brandings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=10), nullable=True),
    sa.Column('secondary_color', sa.String(length=10), nullable=True),
    sa.Column('intro_audio_url', sa.String(length=500), nullable=True),
    sa.Column('outro_audio_url', sa.String(length=500), nullable=True),
    sa.Column('background_url', sa.String(length=500), nullable=True),
    sa.Column('show_name', sa.String(length=200), nullable=True),
    sa.Column('watermark_position', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('podcast_recording_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('invite_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['podcast_episode.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('podcast_recording_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_podcast_recording_session_session_id'), ['session_id'], unique=True)

    op.create_table('podcast_recording_track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_record_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.String(length=100), nullable=False),
    sa.Column('track_type', sa.String(length=50), nullable=True),
    sa.Column('guest_name', sa.String(length=100), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_record_id'], ['podcast_recording_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mastering_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('recording_projects', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('tags',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('bpm',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('time_signature_top',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('time_signature_bottom',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('master_volume',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('metronome_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('count_in_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('duration_seconds',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('sample_rate',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tracks_json',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('track_audio_urls',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('piano_roll_notes_json',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('piano_roll_key',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('piano_roll_scale',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('mixdown_bit_depth',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('mixdown_channels',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('total_size_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('track_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording_projects', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('track_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_size_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('mixdown_channels',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mixdown_bit_depth',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('piano_roll_scale',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('piano_roll_key',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('piano_roll_notes_json',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('track_audio_urls',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('tracks_json',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('sample_rate',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('duration_seconds',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('count_in_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('metronome_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('master_volume',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('time_signature_bottom',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('time_signature_top',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bpm',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tags',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('mastering_jobs', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    op.drop_table('podcast_recording_track')
    with op.batch_alter_table('podcast_recording_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podcast_recording_session_session_id'))

    op.drop_table('podcast_recording_session')
    op.drop_table('studio_brandings')
    op.drop_table('async_recording_links')
    # ### end Alembic commands ###
