"""add advanced ai jobs ledger timeline

Revision ID: 9da939427a69
Revises: 7bb1865d3069
Create Date: 2026-03-19 22:34:49.844648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da939427a69'
down_revision = '7bb1865d3069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_task_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('output_url', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('credits_used', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_task_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_task_jobs_celery_task_id'), ['celery_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_task_jobs_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_task_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_task_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_task_jobs_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_task_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_task_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('video_credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_credit_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_credit_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_credit_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_credit_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('lesson_timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timeline_json', sa.JSON(), nullable=False),
    sa.Column('composed_video_url', sa.String(length=500), nullable=True),
    sa.Column('last_job_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['last_job_id'], ['ai_task_jobs.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_timelines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_timelines_lesson_id'), ['lesson_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_lesson_timelines_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_timelines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_timelines_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_timelines_lesson_id'))

    op.drop_table('lesson_timelines')
    with op.batch_alter_table('video_credit_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_credit_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_video_credit_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_video_credit_transactions_created_at'))

    op.drop_table('video_credit_transactions')
    with op.batch_alter_table('ai_task_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_task_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_task_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_ai_task_jobs_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_ai_task_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_ai_task_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_ai_task_jobs_course_id'))
        batch_op.drop_index(batch_op.f('ix_ai_task_jobs_celery_task_id'))

    op.drop_table('ai_task_jobs')
    # ### end Alembic commands ###
