"""empty message

Revision ID: a8493a68b3fc
Revises: a585475f99a4
Create Date: 2025-03-16 13:52:52.121824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8493a68b3fc'
down_revision = 'a585475f99a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_name', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['artist_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('artist_name')

    # ### end Alembic commands ###
