"""empty message

Revision ID: a8ef2b4248ea
Revises: d4d9c64a4f98
Create Date: 2025-06-21 21:05:24.133832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8ef2b4248ea'
down_revision = 'd4d9c64a4f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('cover_url', sa.String(length=250), nullable=True),
    sa.Column('audio_url', sa.String(length=250), nullable=True),
    sa.Column('is_explicit', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('platform_links', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_studio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_live_chat', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_studio', schema=None) as batch_op:
        batch_op.drop_column('has_live_chat')

    op.drop_table('track_releases')
    # ### end Alembic commands ###
