"""empty message

Revision ID: ae4763329a3e
Revises: f74fe2a6e8f2
Create Date: 2025-07-18 23:08:58.129867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4763329a3e'
down_revision = 'f74fe2a6e8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('podcast_host_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'])
        batch_op.drop_column('host_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('podcast_host_id_fkey'), 'user', ['host_id'], ['id'])
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
