"""Add fields to PricingPlan

Revision ID: b59c8e50187f
Revises: 4298d93fad1a
Create Date: 2025-08-08 00:36:30.048548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b59c8e50187f'
down_revision = '4298d93fad1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_plan')
    with op.batch_alter_table('pricing_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('includes_music_distribution', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sonosuite_access', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('distribution_uploads_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('includes_gaming_features', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('includes_team_rooms', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('includes_squad_finder', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('includes_gaming_analytics', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('includes_game_streaming', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('includes_gaming_monetization', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('includes_video_distribution', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('video_uploads_limit', sa.Integer(), nullable=True))

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('creator_earnings')
        batch_op.drop_column('platform_cut')

    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('monthly_price', sa.Float(), nullable=False))
        batch_op.drop_constraint(batch_op.f('user_subscription_plan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_subscription_plan_id_fkey'), 'subscription_plan', ['plan_id'], ['id'])
        batch_op.drop_column('monthly_price')
        batch_op.drop_column('creator_id')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_cut', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('creator_earnings', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('pricing_plan', schema=None) as batch_op:
        batch_op.drop_column('video_uploads_limit')
        batch_op.drop_column('includes_video_distribution')
        batch_op.drop_column('includes_gaming_monetization')
        batch_op.drop_column('includes_game_streaming')
        batch_op.drop_column('includes_gaming_analytics')
        batch_op.drop_column('includes_squad_finder')
        batch_op.drop_column('includes_team_rooms')
        batch_op.drop_column('includes_gaming_features')
        batch_op.drop_column('distribution_uploads_limit')
        batch_op.drop_column('sonosuite_access')
        batch_op.drop_column('includes_music_distribution')

    op.create_table('subscription_plan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price_monthly', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('price_yearly', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('features', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('includes_podcasts', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('includes_radio', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('platform_cut', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('creator_earnings', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('subscription_plan_pkey')),
    sa.UniqueConstraint('name', name=op.f('subscription_plan_name_key'))
    )
    # ### end Alembic commands ###
