"""empty message

Revision ID: b6832f9c8f54
Revises: 2e773e3e9b99
Create Date: 2026-02-23 00:06:55.649707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6832f9c8f54'
down_revision = '2e773e3e9b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('piano_roll_notes_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('piano_roll_key', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('piano_roll_scale', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording_projects', schema=None) as batch_op:
        batch_op.drop_column('piano_roll_scale')
        batch_op.drop_column('piano_roll_key')
        batch_op.drop_column('piano_roll_notes_json')

    # ### end Alembic commands ###
