"""add daw_sessions table

Revision ID: b951b0a1abaa
Revises: 2f55cf000a0f
Create Date: 2026-03-07 04:15:04.944945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b951b0a1abaa'
down_revision = '2f55cf000a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daw_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('session_code', sa.String(length=20), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('state_json', sa.Text(), nullable=True),
    sa.Column('collaborators_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['recording_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daw_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daw_sessions_session_id'), ['session_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daw_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daw_sessions_session_id'))

    op.drop_table('daw_sessions')
    # ### end Alembic commands ###
