"""empty message

Revision ID: bbb43a30b934
Revises: 4ad21995748e
Create Date: 2025-03-15 00:10:26.002005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb43a30b934'
down_revision = '4ad21995748e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('monetization_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sponsor', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('donation_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('total_revenue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('revenue_from_subscriptions', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('revenue_from_ads', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('revenue_from_sponsorships', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('revenue_from_donations', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stripe_transaction_ids', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('series_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('season_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('episode_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ad_insertion', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('podcast_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['host_id'], ['id'])
        batch_op.drop_column('duration')
        batch_op.drop_column('is_premium')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('podcast_episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast_episode', schema=None) as batch_op:
        batch_op.drop_column('release_date')
        batch_op.drop_column('is_published')

    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('podcast_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('ad_insertion')
        batch_op.drop_column('episode_number')
        batch_op.drop_column('season_number')
        batch_op.drop_column('series_name')
        batch_op.drop_column('stripe_transaction_ids')
        batch_op.drop_column('revenue_from_donations')
        batch_op.drop_column('revenue_from_sponsorships')
        batch_op.drop_column('revenue_from_ads')
        batch_op.drop_column('revenue_from_subscriptions')
        batch_op.drop_column('total_revenue')
        batch_op.drop_column('donation_link')
        batch_op.drop_column('sponsor')
        batch_op.drop_column('monetization_type')
        batch_op.drop_column('host_id')

    # ### end Alembic commands ###
