"""empty message

Revision ID: c5276dcf567a
Revises: 593a08b454dc
Create Date: 2026-02-20 23:03:48.327540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5276dcf567a'
down_revision = '593a08b454dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stem_separation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audio_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('original_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('device_used', sa.String(length=10), nullable=True),
    sa.Column('stem_count', sa.Integer(), nullable=True),
    sa.Column('vocals_url', sa.String(length=500), nullable=True),
    sa.Column('drums_url', sa.String(length=500), nullable=True),
    sa.Column('bass_url', sa.String(length=500), nullable=True),
    sa.Column('guitar_url', sa.String(length=500), nullable=True),
    sa.Column('piano_url', sa.String(length=500), nullable=True),
    sa.Column('other_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audio.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stem_separation_jobs')
    # ### end Alembic commands ###
