"""empty message

Revision ID: e8f5f56cc528
Revises: b2fa993820a7
Create Date: 2025-03-08 15:58:54.628430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f5f56cc528'
down_revision = 'b2fa993820a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('episode_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('streaming_enabled', sa.Boolean(), nullable=True))
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_column('streaming_enabled')
        batch_op.drop_column('episode_number')
        batch_op.drop_column('video_url')
        batch_op.drop_column('audio_url')

    # ### end Alembic commands ###
