"""empty message

Revision ID: ead722e38395
Revises: 1926217b83bd
Create Date: 2025-06-16 00:01:00.205595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead722e38395'
down_revision = '1926217b83bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('enableChat', sa.Boolean(), nullable=True),
    sa.Column('useAvatar', sa.Boolean(), nullable=True),
    sa.Column('enableNotifications', sa.Boolean(), nullable=True),
    sa.Column('emailNotifications', sa.Boolean(), nullable=True),
    sa.Column('darkMode', sa.Boolean(), nullable=True),
    sa.Column('profileVisibility', sa.String(length=50), nullable=True),
    sa.Column('subscriptionPlan', sa.String(length=50), nullable=True),
    sa.Column('twoFactorEnabled', sa.Boolean(), nullable=True),
    sa.Column('payoutMethod', sa.String(length=50), nullable=True),
    sa.Column('defaultStreamQuality', sa.String(length=20), nullable=True),
    sa.Column('defaultVRRoom', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_podcast_follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('podcast_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_podcast_follow')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
