"""empty message

Revision ID: f085bb986405
Revises: d8b5fce38b90
Create Date: 2025-09-09 19:00:22.664957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f085bb986405'
down_revision = 'd8b5fce38b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.String(length=50), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('followed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['radio_station.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'station_id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['stripe_checkout_session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stripe_checkout_session_id')

    op.drop_table('station_follows')
    op.drop_table('podcast_access')
    # ### end Alembic commands ###
