"""empty message

Revision ID: f6e6f75b3603
Revises: a8ef2b4248ea
Create Date: 2025-06-22 03:21:58.675990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e6f75b3603'
down_revision = 'a8ef2b4248ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('genre', sa.String(length=80), nullable=True),
    sa.Column('release_date', sa.String(length=20), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('cover_art_url', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.Column('delivery_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('platform_links', sa.JSON(), nullable=True),
    sa.Column('upc', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaborator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('artist_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_explicit', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lyrics', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('isrc', sa.String(length=50), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('file_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('track_radio_playlist_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('radio_playlist_id')
        batch_op.drop_column('artist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('radio_playlist_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('track_radio_playlist_id_fkey'), 'radio_playlist', ['radio_playlist_id'], ['id'])
        batch_op.alter_column('file_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('isrc')
        batch_op.drop_column('lyrics')
        batch_op.drop_column('is_explicit')
        batch_op.drop_column('genre')
        batch_op.drop_column('artist_name')
        batch_op.drop_column('user_id')

    op.drop_table('collaborator')
    op.drop_table('release')
    # ### end Alembic commands ###
