"""empty message

Revision ID: f74fe2a6e8f2
Revises: a8b9f8e01d62
Create Date: 2025-07-18 22:58:56.097781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74fe2a6e8f2'
down_revision = 'a8b9f8e01d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcription', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('transcription')

    # ### end Alembic commands ###
