"""empty message

Revision ID: fa1b20011f2a
Revises: 94870c1099d1
Create Date: 2026-01-26 02:42:53.377757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1b20011f2a'
down_revision = '94870c1099d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_video_creator', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('channel_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('content_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('channel_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('channel_banner', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('subscriber_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_video_views', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('channel_created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('channel_created_at')
        batch_op.drop_column('total_video_views')
        batch_op.drop_column('subscriber_count')
        batch_op.drop_column('channel_banner')
        batch_op.drop_column('channel_description')
        batch_op.drop_column('content_category')
        batch_op.drop_column('channel_name')
        batch_op.drop_column('is_video_creator')

    # ### end Alembic commands ###
