"""empty message

Revision ID: fd2f7f0ee057
Revises: e529625a7db9
Create Date: 2025-12-22 05:26:30.769664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2f7f0ee057'
down_revision = 'e529625a7db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bandwidth_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bytes_transferred', sa.BigInteger(), nullable=False),
    sa.Column('transfer_type', sa.String(length=20), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bandwidth_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bandwidth_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('transcode_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('output_url', sa.String(length=500), nullable=True),
    sa.Column('output_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('deferred_until_views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_qualities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('is_ready', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'resolution', name='unique_video_resolution')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_qualities')
    op.drop_table('transcode_jobs')
    with op.batch_alter_table('bandwidth_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bandwidth_logs_timestamp'))

    op.drop_table('bandwidth_logs')
    # ### end Alembic commands ###
