import os
from flask_admin import Admin
from api.models import db, User, PodcastEpisode, PodcastSubscription, StreamingHistory, RadioPlaylist, RadioStation, LiveStream, LiveChat, CreatorMembershipTier, CreatorDonation, AdRevenue, UserSubscription, Video, VideoPlaylist, VideoPlaylistVideo, Audio, PlaylistAudio, PricingPlan, Subscription, FavoritePage, Product, RefundRequest, Revenue, Payment, Order, Notification, Comment, Message, Conversation, Group,ShareAnalytics, Like, Tip, Engagement, Earnings, Popularity, Podcast, PodcastHost, PodcastChapter, PodcastPurchase, PodcastClip, RadioDonation, RadioFollower, RadioSubmission, Role, IndieStation, IndieStationTrack, IndieStationFollower, EventTicket, TicketPurchase, VRAccessTicket, Music, Track, LicensingOpportunity, MusicLicensing, Collaboration, Artist, Album, ListeningParty, ListeningPartyAttendee, Stream
from flask_admin.contrib.sqla import ModelView

def setup_admin(app):
    app.secret_key = os.environ.get('FLASK_APP_KEY', 'sample key')
    app.config['FLASK_ADMIN_SWATCH'] = 'cerulean'
    admin = Admin(app, name='StreampireX Admin', template_mode='bootstrap4')

    # Register models in Flask-Admin
    admin.add_view(ModelView(User, db.session))
    admin.add_view(ModelView(PodcastEpisode, db.session))
    admin.add_view(ModelView(PodcastSubscription, db.session))
    admin.add_view(ModelView(StreamingHistory, db.session))
    admin.add_view(ModelView(RadioPlaylist, db.session))
    admin.add_view(ModelView(RadioStation, db.session))
    admin.add_view(ModelView(LiveStream, db.session))
    admin.add_view(ModelView(LiveChat, db.session))
    admin.add_view(ModelView(CreatorMembershipTier, db.session))
    admin.add_view(ModelView(CreatorDonation, db.session))
    admin.add_view(ModelView(AdRevenue, db.session))
    admin.add_view(ModelView(UserSubscription, db.session))
    admin.add_view(ModelView(Video, db.session))
    admin.add_view(ModelView(VideoPlaylist, db.session))
    admin.add_view(ModelView(VideoPlaylistVideo, db.session))
    admin.add_view(ModelView(Audio, db.session))
    admin.add_view(ModelView(PlaylistAudio, db.session))
    admin.add_view(ModelView(PricingPlan, db.session))
    admin.add_view(ModelView(Subscription, db.session))
    admin.add_view(ModelView(FavoritePage, db.session))
    admin.add_view(ModelView(Product, db.session))
    admin.add_view(ModelView(RefundRequest, db.session))
    admin.add_view(ModelView(Revenue, db.session))
    admin.add_view(ModelView(Payment, db.session))
    admin.add_view(ModelView(Order, db.session))
    admin.add_view(ModelView(Notification, db.session))
    admin.add_view(ModelView(Comment, db.session))
    admin.add_view(ModelView(Message, db.session))
    admin.add_view(ModelView(Conversation, db.session))
    admin.add_view(ModelView(Group, db.session))
    admin.add_view(ModelView(ShareAnalytics, db.session))
    admin.add_view(ModelView(Like, db.session))
    admin.add_view(ModelView(Tip, db.session))
    admin.add_view(ModelView(Engagement, db.session))
    admin.add_view(ModelView(Earnings, db.session))
    admin.add_view(ModelView(Popularity, db.session))
    admin.add_view(ModelView(Podcast, db.session))
    admin.add_view(ModelView(PodcastHost, db.session))
    admin.add_view(ModelView(PodcastChapter, db.session))
    admin.add_view(ModelView(PodcastPurchase, db.session))
    admin.add_view(ModelView(PodcastClip, db.session))
    admin.add_view(ModelView(RadioDonation, db.session))
    admin.add_view(ModelView(RadioFollower, db.session))
    admin.add_view(ModelView(RadioSubmission, db.session))
    admin.add_view(ModelView(Role, db.session))
    admin.add_view(ModelView(IndieStation, db.session))
    admin.add_view(ModelView(IndieStationTrack, db.session))
    admin.add_view(ModelView(IndieStationFollower, db.session))
    admin.add_view(ModelView(EventTicket, db.session))
    admin.add_view(ModelView(TicketPurchase, db.session))
    admin.add_view(ModelView(VRAccessTicket, db.session))
    admin.add_view(ModelView(Music, db.session))
    admin.add_view(ModelView(Track, db.session))
    admin.add_view(ModelView(LicensingOpportunity, db.session))
    admin.add_view(ModelView(MusicLicensing, db.session))
    admin.add_view(ModelView(Collaboration, db.session))
    admin.add_view(ModelView(Artist, db.session))
    admin.add_view(ModelView(Album, db.session))
    admin.add_view(ModelView(ListeningParty, db.session))
    admin.add_view(ModelView(ListeningPartyAttendee, db.session))
    admin.add_view(ModelView(Stream, db.session))
